aki_analytics_range = {'BUN': {'normal_range': (10, 20),
                               'aki': (20),
                               'atn': (15)},
                       'Sodium': {'normal_range': (135, 145),
                                  'aki': (),
                                  'atn': ()},
                       'Potassium': {'normal_range': (3.7, 5.2),
                                     'aki': (),
                                     'atn': ()},
                       'Creatinine': {'normal_range': (0.6, 1.3),
                                      'aki': (),
                                      'atn': ()},
                       'Bilirubin': {'normal_range': (0.1, 1.2),
                                     'aki': (),
                                     'atn': ()},
                       'Urine_specific_gravity': {'normal_range': (1.012, 1.018),
                                                  'aki': (1.018),
                                                  'atn': (1.012)},
                       'Urine_osmolality': {'normal_range': (800, 1400),
                                            'aki': (500),
                                            'atn': (500)},
                       'Urine_sodium': {'normal_range': (20, 40),
                                        'aki': (20),
                                        'atn': (40)},
                       'Urine_protein': {'normal_range': (0, 30),
                                         'aki': (),
                                         'atn': ()},
                       'Urine_creatinine': {'normal_range': (20, 40),
                                            'aki': (40),
                                            'atn': (20)},
                       'Urine_volume': {'normal_range': (0.5, None),
                                        'aki': (),
                                        'atn': ()},
                       }

pneumonia_analytics_range = {'WBC': {'pneumonia': (4, 12),
                                     },
                             'Immature_gran': {'pneumonia': (0, 1)},
                             'Fever': {'pneumonia': (96.8, 101)},
                             'Procalcitonin': {'pneumonia': (None, 0.25)},
                             'CRP': {'pneumonia': (None, 400)},
                             }
