
section_list = ['Summary Discharge Report', 'Provider - Discharge Notes',
                'Progress/Discharge Note Pt', 'Progress/Discharge Note Ot',
                'Physician Discharge Summary', 'Patient Discharge Instructions',
                'Medication Discharge Summary', 'Inpatient Discharge Instructions',
                'Hospitalist Discharge Summary', 'Hospital Discharge Summary',
                'Fmc Discharge Summary', 'Discharge Summary:',
                'Discharge Summary Note (Continued)', 'Discharge Summary Note',
                'Discharge Summary (Inpatient) Advanced Practice Provider-Dis',
                'Discharge Summary (Continued)', 'Discharge Summary',
                'Discharge Summaries (Continued)', 'Discharge Summaries',
                'Discharge Recommendations', 'Discharge Planner Note',
                'Discharge Note', 'Discharge Medication List',
                'Discharge Instructions', 'Discharge Information (Continued)',
                'Discharge Information', 'Discharge Documentation',
                'Death Summary', 'Admit/Transfer/Discharge Orders',
                'Admit, Discharge, Transfer Forms',
                'Admission/Discharge Information', 'Discharge Quick Note',
                'Discharge Summary Inpatient (LH) - Discharge Summary',
                'Discharge Summary Documents',
                'Emergency/Urgent Care', 'Emergency/Trauma Documentation',
                'Emergency Report', 'Emergency Provider Report',
                'Emergency Medicine', 'Emergency Documentations',
                'Emergency Documentation', 'Emergency Department Reports',
                'Emergency Department Chart', 'Ed To Hosp-Admission', 'Ed Records',
                'Ed Record', 'Ed Provider Notes - Ed Notes', 'Ed Provider Note',
                'Ed Patient Discharge Information', 'Ed Notes',
                'Ed Note-Physician', 'Emergency Department Provider Note',
                'Emergency Department Provider Note (Continued)',
                'Ed Care Timeline (Continued)', 'Ed Care Timeline',
                'Emergency Department Patient Education',
                'Emergency Department Triage',
                'Emergency Department History/Social',
                'Emergency Department Depart',
                'Emergency Department Provider Report',
                'Emergency Department Provider Documentation', 'Provider Note ED',
                'Triage - ED', 'ED Patient Care Timeline Report']
suppress_date_tag = ['registration date',
                     'discharge date',
                     'dischg date',
                     'admit date',
                     'admit dt',
                     'adm date',
                     'dis date',
                     'dis dt',
                     'adm',
                     'd c',
                     'discharge service',
                     'admission date',
                     'admitted',
                     'visit date',
                     'date of visit',
                     'eff date',
                     'adm date',
                     'date of admission',
                     'discharge date',
                     'date of admission',
                     'date of discharge',
                     'visit date',
                     'date of birth',
                     'admit date',
                     'admit date time',
                     'date of visit',
                     'admission date',
                     'arrival date',
                     'date of birth',
                     'dob',
                     'printed',
                     'generated',
                     'printed by',
                     'date time printed',
                     'admitted',
                     'action date time',
                     'order start date time',
                     'order date time']

suppress_date_without_adm_disch = ['visit date', 'filed', 'creation time', 'date of visit', 'arrival date', 'date of birth',
                                   'dob', 'printed', 'generated', 'printed by', 'date time printed', 'order start date time', 'order date time']
date_tags = ['date of last dressing change',
             'electronically witnessed',
             'hospital course to date',
             'observation start date',
             'order start date time',
             'electronically signed',
             'date of consultation',
             'date of consultation',
             'date time of service',
             'end state date time',
             'collected date time',
             'datetime of service',
             'verified date time',
             'received date time',
             'collected datetime',
             'date of collection',
             'date time printed',
             'received datetime',
             'service date time',
             'consultation date',
             'last liquids date',
             'date of discharge',
             'date of admission',
             'date of admission',
             'discharge service',
             'registration date',
             'date of procedure',
             'action date time',
             'authenticated by',
             'performance date',
             'transfusion date',
             'last solids date',
             'dischargeservice',
             'dates of service',
             'servie date time',
             'dt tm of service',
             'order date time',
             'admin date time',
             'order date time',
             'print date time',
             'requesting date',
             'expiration date',
             'evaluation date',
             'admit date time',
             'expiration date',
             'abs status date',
             'drg status date',
             'date of service',
             'servie datetime',
             'dttm of service',
             'exam date time',
             'procedure date',
             'requested date',
             'admission date',
             'completed date',
             'discharge date',
             'admission date',
             'discharge date',
             'procedure date',
             'due date time',
             'creation time',
             'transcribv by',
             'transcribe by',
             'date of birth',
             'date of study',
             'date and time',
             'date of onset',
             'date of visit',
             'activity date',
             'date of birth',
             'run date time',
             'date of visit',
             'service dt tm',
             'dt of service',
             'service dates',
             'date printed',
             'arrival date',
             'receipt date',
             'collect date',
             'date written',
             'last updated',
             'service_date',
             'request date',
             'service date',
             'service dttm',
             'result date',
             'authored by',
             'reviewed by',
             'consults by',
             'addendum by',
             'triage date',
             'result date',
             'dischg date',
             'order dt tm',
             'printed by',
             'admit date',
             'study date',
             'order date',
             'visit date',
             'visit date',
             'order date',
             'start date',
             'admit date',
             'service dt',
             'order dttm',
             'verify by',
             'signed on',
             'signed by',
             'review by',
             'edited by',
             'generated',
             'oper date',
             'exam date',
             'resulted',
             'dictated',
             'addendum',
             'added by',
             'date run',
             'run date',
             'adm date',
             'eff date',
             'admitted',
             'dis date',
             'end date',
             'adm date',
             'admit dt',
             'sign by',
             'perform',
             'printed',
             'dis dt',
             'filed',
             'sent',
             'dob',
             'adm',
             'dos',
             'dc']

precedence_dict = {'collected date time': 1, 'collected datetime': 1, 'collect date': 1,  'date of collection': 1,
                   'result date': 2, 'resulted': 2, 'resulted date': 2,
                   'observation start date': 3, 'study date': 3,
                   'perform': 4, 'procedure date': 4, 'performance date': 4,
                   'received datetime': 5, 'received date time': 5,
                   'exam date time': 6,
                   'action date time': 7,
                   'service date time': 7, 'date of consultation': 7, 'creation time': 7, 'verified date time': 7,
                   'requested date': 7, 'date written': 7, 'receipt date': 7, 'run date time': 7,
                   'recorded date': 7,
                   }
