date_tags = [
    'date time of service',
    'datetime of service',
    'date of procedure',
    'registration date',
    'dt tm of service',
    'dttm of service',
    'servie date time',
    'servie datetime',
    'dates of service',
    'document date time', 
    'date of service',
    'procedure date',
    'discharge date',
    'service dates',
    'dt of service',
    'service dttm',
    'service dt tm',
    'service date',
    'request date',
    'order dttm',
    'order dt tm',
    'dischg date',
    'service dt',
    'admit date',
    'start date',
    'order date',
    'exam date',
    'admit dt',
    'adm date',
    'end date',
    'dis date',
    'dis dt',
    'dos',
    'adm',
    'dc',
    'discharge service',
    'dischargeservice',
    'admission date',
    'admitted',
    'visit date',
    'date of visit',
    'service_date',
    'EFF DATE',
    'ADM DATE',
    'RUN DATE',
    'DRG STATUS DATE',
    'ABS STATUS DATE',
    'Date of admission',
    'Observation Start Date',
    'Discharge date',
    'DATE OF ADMISSION',
    'DATE OF DISCHARGE',
    'Visit Date',
    'DATE OF CONSULTATION',
    'Hospital course to date',
    'Run Date Time',
    'Date Run',
    'Order Date',
    'Date of Birth',
    'Oper Date',
    'Last Updated',
    'Last solids date',
    'Last liquids date',
    'Completed Date',
    'expiration date',
    'Study Date',
    'ADMIT DATE',
    'Activity Date',
    'Date of last dressing change',
    'Admit Date Time',
    'Result Date',
    'Date of Visit',
    'Admission Date',
    'Date of Onset',
    'Transfusion Date',
    'Evaluation Date',
    'EXPIRATION DATE',
    'DATE AND TIME',
    'Performance Date',
    'Requesting Date',
    'Date of Collection',
    'Requested Date',
    'Date Written',
    'Collect Date',
    'Receipt Date',
    'Procedure Date',
    'Date of Study',
    'Arrival Date',
    'Triage Date',
    'CONSULTATION DATE',
    'Date of birth',
    'DOB',
    'printed', 'generated',
    'printed by',
    'added by',
    'addendum',
    'addendum by',
    'authenticated by',
    'consults by',
    'edited by',
    'electronically signed',
    'electronically witnessed',
    'perform',
    'review by',
    'reviewed by',
    'sign by',
    'signed by',
    'signed on',
    'transcribe by',
    'transcribv by',
    'verify by',
    'authored by',
    'filed',
    'print date time',
    'service date time',
    'date of consultation',
    'creation time',
    'collected date time',
    'collected datetime',
    'received datetime',
    'received date time',
    'verified date time',
    'exam date time',
    'due date time',
    'order date time',
    'end state date time',
    'admin date time',
    'dictated',
    'sent',
    'date time printed',
    'date printed',
    'action date time',
    'est',
    'order start date time',
    'order date time', 
    'received date time',
    'date of surgery',
    ]

adm_dis_tag = ['discharge date',
               'dischg date',
               'admit date',
               'admit dt',
               'adm date',
               'dis date',
               'dis dt',
               'adm',
               'discharge/service',
               'admission date',
               'admitted',
               'Date of admission']

suppress_date_tag_section_end = [
    'registration date',
    'discharge date',
    'dischg date',
    'admit date',
    'admit dt',
    'adm date',
    'dis date',
    'dis dt',
    'adm',
    'd/c',
    'discharge/service',
    'admission date',
    'admitted',
    'visit date',
    'date of visit',
    'EFF DATE',
    'ADM DATE',
    'Date of admission',
    'Discharge date',
    'DATE OF ADMISSION',
    'DATE OF DISCHARGE',
    'Visit Date',
    'Date of Birth',
    'ADMIT DATE',
    'Admit Date Time',
    'Date of Visit',
    'Admission Date',
    'Arrival Date',
    'Date of birth',
    'DOB',
    'printed', 
    'generated',
    'printed by',
    'date time printed',
    'admitted',
    'action date time',
    'est',
    'order start date time',
    'order date time',
    ]

suppress_date_tag_section = [
    'discharge date',
    'dischg date',
    'end date',
    'dis date',
    'dis dt',

    'discharge/service',
    'admission date',

    'Date of admission:',

    'Discharge date',

    'DATE OF DISCHARGE',

    'Date of Birth',

    'Completed Date',
    'expiration date',

    'EXPIRATION DATE',

    'Date of birth',
    'DOB',
    'printed',

    'added by',
    'addendum',
    'addendum by',
    'authenticated by',
    'consults by',
    'edited by',
    'electronically signed',
    'electronically witnessed',
    'perform',
    'review by',
    'reviewed by',
    'sign by',
    'signed by',
    'signed on',
    'transcribe by',
    'transcribv by',
    'verify by']

section_date_tags = ['date of service',
                     'service date',
                     'service dates', 
                     'service date time',
                     'date of consultation', 
                     'document date time', 
                     'received date time',
                     'date of procedure', 
                     'date of surgery']

demographics_ls = ['registration/demographic information',
 'date(s) of service of claim',
 'patient account number',
 'employment information',
 'guarantor information',
 'contact information',
 'notify information',
 'notify home phone',
 'educational level',
 'notify state/zip',
 'guar  home phone',
 "patient's name",
 'patient number',
 'notify address',
 'member/patient',
 'marital status',
 'insurance plan',
 'guarantor name',
 'account number',
 'religion name',
 'policy number',
 'patient phone',
 'notify person',
 'mobile number',
 'guar rel name',
 'guar emp name',
 'date of birth',
 'work phone #',
 'phone number',
 'patient name',
 'member idage',
 'home address',
 'guar address',
 'claim number',
 'notify city',
 'nationality',
 'home phone:',
 'profession',
 'occupation',
 'employment',
 'guar name',
 'birthdate',
 'religion',
 'location',
 'district',
 'account#',
 'patient',
 'country',
 'claim #',
 'address',
 'phone#',
 'gender',
 'name',
 'fin#',
 'area',
 'sex',
 'mmi',
 'dob']

section_end_date_tags = [
 'electronically witnessed',
 'electronically signed',
 'testing performed by',
 'electronic signature',
 'authenticated by',
 'end of document',
 'transcribed by',
 'transcribv by',
 'transcribe by',
 'authorized by',
 'performed by',
 'addendum by',
 'consults by',
 'entered by',
 'signed by',
 'edited by',
 'review by',
 'verify by',
 'signed on',
 'added by',
 'sign by']

date_tags_regex_dict = {
                        'exam_date_time': r"exam\s?(?:date)\s?\/?\s?(?:time)",
                        'received' : r"received\s?(?:by)?(?:date)?\s?\/?\s?(?:time)?",
                        'collect_date_time' : r"collect(?:ed)?\s?(?:by)?\s?(?:date)?\s?\/?\s?(?:time)?",
                        'result_date_time' : r"result(?:ed)?\s?(?:by)?\s?(?:date)?\s?\/?\s?(?:time)?"
                        }