pnm_antibiotics_antiviral_ls = ['penicillin v potassium tablet, film coated', 'azithromycin tablet, film coated', 'sulfamethoxazole and trimethoprim tablet', 'azithromycin (azithromycin monohydrate) powder, for suspension', 'cephalexin capsule', 'ciprofloxacin tablet', 'fluconazole tablet', 'ciprofloxacin (ciprofloxacin hydrochloride) tablet, film coated', 'clarithromycin tablet, film coated', 'ciprofloxacin tablet, film coated', 'ery-tab (erythromycin) tablet, delayed release', 'levofloxacin tablet, film coated', 'cefdinir powder, for suspension', 'prednisolone sodium phosphate solution', 'avelox abc pack (moxifloxacin hydrochloride) tablet, film coated', 'sulfamethoxazole and trimethoprim ds tablet', 'azithromycin (azithromycin) tablet, film coated', 'sulfamethoxazole and trimethoprim suspension', 'ciprofloxacin tablet, coated', 'ciprofloxacin hydrochloride tablet', 'metronidazole tablet', 'ketek (telithromycin) tablet, film coated', 'cefdinir capsule', 'clarithromycin tablet', 'erythromycin ethylsuccinate tablet', 'bactrim ds (sulfamethoxazole and trimethoprim) tablet', 'penicillin v potassium powder, for solution', 'augmentinxr (amoxicillin and clavulanate potassium) tablet, film coated, extended release', 'erythromycin base filmtab (erythromycin) tablet, film coated', 'ciprofloxacin injection', 'zyvox (linezolid) tablet, film coated', 'erythromycin tablet, film coated', 'zmax (azithromycin) powder, for suspension', 'erythromycin capsule, delayed release', 'clindamycin phosphate injection, solution', 'penicillin v potassium tablet', 'cefaclor capsule', 'levaquin (levofloxacin) tablet, film coated', 'ciprofloxacin hydrochloride (ciprofloxacin hydrochloride tablet) tablet', 'ciprofloxacin hydrochloride (ciprofloxacin hydrochloride) tablet, film coated', 'ciprofloxacin injection, solution, concentrate', 'avelox (moxifloxacin hydrochloride) tablet, film coated', 'cefaclor suspension', 'sulfamethoxazole and trimethoprim (sulfamethoxazole and trimethoprim) tablet', 'cefdinir (cefdinir) capsule', 'ciprofloxacin (ciprofloxacin hydrochloride) tablet', 'clarithromycin tablet, film coated, extended release', 'biaxin (clarithromycin) tablet, film coated biaxin (clarithromycin) tablet, film coated, extended release biaxin (clarithromycin) granule, for suspension', 'bicillin cr (penicillin g benzathine and penicillin g procaine) injection, suspension', 'azithromycin powder, for suspension', 'tyvaso dpi (treprostinil) inhalant tyvaso dpi (treprostinil) kit', 'acetylcysteine solution', 'metronidazole (metronidazole) tablet', 'clarithromycin tablet, coated', 'erythrocin stearate (erythromycin stearate) tablet, film coated', 'levofloxacin tablet', 'azithromycin monohydrate tablet, film coated', 'levofloxacin solution', 'zyvox (linezolid) suspension', 'levaquin (levofloxacin) tablet', 'azithromycin tablet, film coated azithromycin powder, for suspension', 'fluconazole tablet fluconazole powder, for suspension', 'azithromycin dihydrate (azithromycin) tablet, film coated', 'sulfatrim (sulfamethoxazole and trimethoprim) suspension', 'penicillin v potasium tablet', 'zithromax (azithromycin) tablet', 'clarithromycin for suspension', 'metronidazole tablet, film coated', 'azithromycin dihydrate tablet, film coated', 'erythromycin base (erythromycin) tablet, film coated', 'azithromycin monohydrate tablet', 'atovaquone suspension', 'metronidazole500 mg 500 mg (metronidazole) tablet, film coated', 'metronidazole250 mg 250 mg (metronidazole) tablet, film coated', 'sulfatrim suspension', 'moxifloxacin hydrochloride tablet, film coated', 'prevnar 13 (pneumococcal 13-valent conjugate vaccine) injection, suspension', 'daptomycin injection, powder, lyophilized, for suspension', 'ciprofloxacin in dextrose (ciprofloxacin) injection, solution', 'erythromycin ethylsuccinate suspension', 'gentamicin injection, solution', 'piperacillin and tazobactam injection, powder, for solution', 'sulfameth/trimeth-ds tablet', 'erythromycin ethylsuccinate for suspension', 'erythromycin tablet, delayed release', 'ciprofloxacin (ciprofloxacin hydrochloride ) tablet, film coated', 'cleocin phosphate (clindamycin phosphate) injection, solution', 'ciprofloxacin tablet ciprofloxacin tablet', 'moxifloxacin hydrochloride (moxifloxacin hydrochloride) tablet, film coated', 'moxifloxacin tablet, film coated', 'clarithromycin 500 mg (clarithromycin) tablet, film coated', 'zithromax (azithromycin) tablet, film coated', 'acetylcysteine inhalant', 'azithromycin (azithromycin monohydrate) tablet, film coated', 'ciprofloxacin (ciprofloxacin tablets) tablet, coated', 'sulfamethox-tmp ds (sulfamethoxazole, trimethoprim) tablet', 'clindamycin (clindamycin phosphate) injection, solution, concentrate', 'gentamicin sulfate injection, solution', 'levofloxacin tablet levofloxacin tablet, film coated', 'clindamycin (clindamycin phosphate) injection, solution', 'ceftiflex (ceftiofur sodium) injection, powder, for solution', 'linezolid tablet, film coated', 'dapzura rt (daptomycin) injection, powder, lyophilized, for solution', 'flagyl (metronidazole) tablet, film coated', 'zosyn (piperacillin sodium and tazobactam sodium) injection, solution', 'spectogard (spectinomycin sulfate) injection, solution', 'zithromax (azithromycin dihydrate) tablet, film coated', 'moxifloxacin hydrochloride tablet', 'sulfamethoxazole and trimethoprim ds (sulfamethoxazole and trimethoprim) tablet', 'ciprofloxacin hcl tablet, film coated', 'metronidazole injection, solution', 'moxifloxacin (moxifloxacin) tablet, film coated', 'ciprofloxacin injection, solution', 'daptomycin in sodium chloride injection, solution', 'metronidazole250', 'erythromycin', 'cephalexin', 'ceftiflex', 'pneumococcal', 'sulfatrim', 'daptomycin', 'prevnar', 'conjugate', 'cefaclor', 'treprostinil', 'clavulanate', 'piperacillin', 'bactrim', 'telithromycin', 'ketek', 'clindamycin', 'augmentinxr', 'ceftiofur', 'spectinomycin', 'metronidazole500', 'acetylcysteine', 'tazobactam', 'ethylsuccinate', 'moxifloxacin', 'ciprofloxacin', 'erythromycin stearate', 'benzathine', 'sulfamethoxazole', 'cefdinir', 'clarithromycin', 'lyophilized,', 'amoxicillin', 'gentamicin', 'biaxin', 'azithromycin dihydrate', 'procaine', 'linezolid', 'levofloxacin', 'trimethoprim', 'flagyl', 'bicillin', 'prednisolone', 'ciprofloxacin in dextrose', 'avelox', 'zithromax', 'zmax', 'penicillin', 'cleocin', 'inhalant tyvaso dpi', 'dapzura', 'erythrocin', 'levaquin', 'azithromycin', 'zyvox', 'sulfamethox-tmp', 'spectogard', 'sulfameth/trimeth-ds', 'atovaquone', 'monohydrate', 'metronidazole', 'fluconazole', 'zosyn']
pneumonia_attribute_dict = {'Chest xray (CXR)': {'generic_term': ['Identify opacity', 'infiltrates', 'consolidations', 'caviations', 'increased density',  'opacification', 'shadowing'],
                                       'spacific_term': ['Chest xray', 'cxr', 'Chest Radiograph', 'Chest x-ray single view', 'xr chest', 'Chest x-ray', 'chest', 'Radiograph', 'Thorax'],
                                       'color': (255, 210, 77),

                                       },
                  'CT Scan Chest (CT Chest)': {'generic_term': ['Identify opacity', 'infiltrates', 'consolidations', 'caviations', 'increased density',  'opacification', 'shadowing'],
                                               'spacific_term': ['CT Scan Chest (CT Chest)', 'CT Scan', 'CT Chest', 'Scan Chest', 'Chest Scan'],
                                               'color': (255, 210, 77), },
                  'Lung Ultrasound (US)': {'generic_term': ['Lung Ultrasound (US)', 'Identify opacity', 'infiltrates', 'consolidations', 'caviations', 'increased density',  'opacification', 'hyperechogenic'],
                                           'spacific_term': ['Lung Ultrasound (US)', 'hyperechogenic', 'Lung Ultrasound',],
                                           'color': (255, 210, 77), },

                  'Sputum Production': {'generic_term': ['Wet cough', 'Productive cough'],
                                        'spacific_term': ['Sputum production', 'Expectoration',],
                                        'color': (172, 208, 149), },
                  'Chest wall splinting': {'generic_term': [],
                                           'spacific_term': ['Chest wall splinting', 'Respiratory splinting', 'pillow splinting', 'manual splinting'],
                                           'color': (172, 208, 149),
                                           },
                  'Chills': {'generic_term': [],
                             'spacific_term': ['Chills', 'rigors'],
                             'color': (172, 208, 149),
                             },
                  'Cough': {'generic_term': [],
                            'spacific_term': ['Cough', 'tussis'],
                            'color': (172, 208, 149),
                            },
                  'Dullness to percussion': {'generic_term': [],
                                             'spacific_term': ['Dullness to percussion'],
                                             'color': (172, 208, 149),
                                             },
                  'Egophony': {'generic_term': [],
                               'spacific_term': ['Egophony', 'aegophony', 'capriloquism', 'tragophonia', 'tragophony', 'egobronchophony'],
                               'color': (172, 208, 149),
                               },
                  'Mechanical Ventilation': {'generic_term': ['Noninvasive positive pressure ventilation', 'NPPV', 'CPAP',  'Bilevel positive airway pressure',  'BiPAP',  'Negative pressure ventilation', 'NPV',  'Mechanical ventilation with heat recovery', 'MVHR', 'High flow nasal cannula', 'CMV', 'IMV', 'peep', 'PSV', 'SIMV'],
                                             'spacific_term': ['Mechanical Ventilation', 'vent', 'Invasive mechanical ventilation', 'controlled mechanical ventilation', 'Invasive positive pressure ventilation', 'IPPV',  'Intermittent mandatory ventilation', 'Positive end expiratory pressure', 'Synchronized intermittent mandatory ventilation', 'SIMV',   'Assist Control', 'Volume limited assist control ventilation', 'VAC', 'Pressure limited assist control ventilation', 'PAC', 'Continuous positive airway pressure', 'CMV', 'IMV', 'peep', 'PSV', 'SIMV', 'endotracheal tube', 'tracheostomy', 'trach'
                                                               'Intubation', 'Extubation', 'Spontaneous', 'Breathing trial', 'SBT', 'Weaning'],
                                             'color': (247, 193, 161),
                                             },
                  'Fever': {'generic_term': [],
                            'spacific_term': ['fever', 'pyrexia', 'febrile'],
                            'color': (172, 208, 149),
                            },
                  'Pleural rub': {'generic_term': [],
                                  'spacific_term': ['Pleural rub', 'pleural friction rub'],
                                  'color': (172, 208, 149),
                                  },
                  'Pneumonia': {'generic_term': [],
                                'spacific_term': ['Pneumonia', 'pneumonitis', 'PNA', 'HCAP', 'HAP', 'CAP', 'VAP',
                                                  'Healthcare associated pneumonia', 'Hospital acquired pneumonia',
                                                  'Community acquired pneumonia', 'Ventilatory-associated pneumonia',
                                                  'Nosocromial pneumonia', 'Aspiration pneumonia', 'bronchopneumonia', 'lobar pneumonia',
                                                  'Bacterial pneumonia', ' Fungal pneumonia', 'Viral pneumonia'],
                                'color': (128, 255, 128),
                                },

                  'Pleuritic chest pain': {'generic_term': [],
                                           'spacific_term': ['Pleuritic chest pain'],
                                           'color': (172, 208, 149),
                                           },
                  'Rales (Crackles)': {'generic_term': [],
                                       'spacific_term': ['Rales (Crackles)', 'rales', 'Crackles', 'Fine crackles',
                                                         'Coarse crackles', 'Rattling sounds in lungs heard on inhalation'],
                                       'color': (172, 208, 149),
                                       },
                  'Rhonchi': {'generic_term': [],
                              'spacific_term': ['Rhonchi', 'Rhoncus'],
                              'color': (172, 208, 149),
                              },
                  'Shortness of Breath': {'generic_term': [],
                                          'spacific_term': ['Shortness of Breath', 'breathlessness', 'dyspnea',
                                                            'air hunger', 'labored breathing', 'tachypnea'],
                                          'color': (172, 208, 149),
                                          },
                  'Supplemental Oxygen': {'generic_term': ['Noninvasive positive pressure ventilation', 'NPPV', 'Continuous positive airway pressure', 'CPAP', 'Bilevel positive airway pressure',  'BiPAP',  'Negative pressure ventilation', 'NPV',  'Mechanical ventilation with heat recovery', 'MVHR', 'High flow nasal cannula',],
                                          'spacific_term': ['Supplemental Oxygen', 'O2', 'nasal cannula', 'simple face mask', 'partial rebreather mask', 'non rebreather mask', 'venturi mask'],
                                          'color': (173, 206, 235),
                                          },
                  'Tachycardia': {'generic_term': [],
                                  'spacific_term': ['Tachycardia',],
                                  'color': (172, 208, 149),
                                  },
                  'Tactile fremitus': {'generic_term': [],
                                       'spacific_term': ['Tactile fremitus', 'tactile vocal fremitus'],
                                       'color': (172, 208, 149),
                                       },
                  'Procalcitonin': {'generic_term': [],
                                    'spacific_term': ['pct', 'procalcitonin'],
                                    'color': (153, 170, 255),
                                    },
                  'PCR Rapid Influenza': {'generic_term': [],
                                          'spacific_term': ['Pcr Rapid Influenza', 'Influenza', 'Influenzae',],
                                          'color': (153, 170, 255),
                                          },
                  'Gram Stain': {'generic_term': [],
                                 'spacific_term': ['gram stain', 'g+ stain'],
                                 'color': (153, 170, 255),
                                 },
                  'Leukocytosis': {'generic_term': [],
                                   'spacific_term': ['Leukocytosis',],
                                   'color': (153, 170, 255),
                                   },
                  'PCR Urine Antigen (UAT)': {'generic_term': [],
                                              'spacific_term': ['Pcr Urine Antigen (UAT)', 'UAT', 'urine pcr', 'pcr urine', 'urine antigen'],
                                              'color': (153, 170, 255),
                                              },
                  'Sputum Culture': {'generic_term': [],
                                     'spacific_term': ['Sputum Culture', 'Sputum Cx'],
                                     'color': (153, 170, 255),
                                     },

                  'Bands': {'generic_term': [],
                            'spacific_term': ['Bands', 'immature granulocytes', 'granulocytes', 'left-shift', 'Imm gran', 'stab cells'
                                              'immature neutrophils', 'bandemia'],
                            'color': (172, 208, 149),
                            },
                  'Blood Culture': {'generic_term': [],
                                    'spacific_term': ['Blood Culture', 'blood cx', 'Bld Cx'],
                                    'color': (255, 210, 77),
                                    },
                  'CMP': {'generic_term': [],
                                'spacific_term': ['Chemistry Panel', 'Basic Metabolic Panel', 'Comprehensive Metabolic Panel', 'Metabolic Panel', 'BMP', 'CMP', 'CHEM', 'CHEM 8'],
                                'color': (153, 170, 255),
                                },
                  'CBC': {'generic_term': [],
                          'spacific_term': ['wbc', 'White Blood Cell',],
                          'color': (153, 170, 255),
                          },

                  'CRP': {'generic_term': [],
                          'spacific_term': ['c reactive protein', 'CRP', 'C-reactive protein'],
                          'color': (255, 210, 77),
                          },
                  'Antiviral_Antifungal_Antibiotics': {'generic_term': [],
                                                       'spacific_term': ['Antiviral', 'Antifungal', 'Antibiotics', 'Abx']+pnm_antibiotics_antiviral_ls,
                                                       'color': (173, 206, 235),
                                                       },

                  }
pneumonia_attribute_regex_dict = {'Procalcitonin': r"\b(?:procalcitonin|pct)\b\s*(?:[^0-9]*)?\s*(\d{1,}\.?\d{1,})\s(?:.*?)?\s([a-z]+\/[a-z]+)?",
                             'CRP': r"\b(?:c(?:-)?\s?reactive protein|crp)\b\s*(?:[^0-9]*)?\s*(\d{1,}\.?\d{1,})\s?(?:.*?)?\s?([a-z]+\/[a-z]+)?",
                             'Fever': r"(?:temp|fever|febrile)\s*(?:[^0-9]*)?\s*(\d{1,}\.?\d{1,})\s?"}
pneumonia_lab_list = ['blood_culture', 'sputum']

aki_attribute_dict = {'Acute_kidney_injury': {'generic_term': [],
                                          'spacific_term': ['acute kidney injury', 'AKI', 'ARF', 'acute renel failure'],
                                          'color': (128, 255, 128),

                                          },
                  'Acute_tubular_necrosis': {'generic_term': [],
                                             'spacific_term': ['acute tubular necrosis', 'ATN'],
                                             'color': (128, 255, 128),

                                             },
                  'Apply_renal_dosing': {'generic_term': [],
                                         'spacific_term': ['apply renal dosing',],
                                         'color': (173, 206, 235),

                                         },
                  'Baseline_serum_creatinine': {'generic_term': [],
                                                'spacific_term': ['baseline serum creatinine', 'baseline creatinine', 'creatinine at baseline',
                                                                  'CKD (baseline)', 'CKD-baseline cr'],
                                                'color': (255, 210, 77),

                                                },
                  'Blood_urea_nitrogen': {'generic_term': [],
                                          'spacific_term': ['blood urea nitrogen', 'BUN', 'BUN/Cr', 'Bun/Creat'],
                                          'color': (255, 210, 77),
                                          },
                  'Discontinue_nephrotoxins': {'generic_term': [],
                                               'spacific_term': ['discontinue nephrotoxins', 'nephrotoxin'],
                                               'color': (173, 206, 235),
                                               },
                  'Diuretics': {'generic_term': [],
                                'spacific_term': ['diuretics'],
                                'color': (173, 206, 235),
                                },
                  'Fractional_excretion_of_sodium': {'generic_term': [],
                                                     'spacific_term': ['fractional excretion of sodium', 'FeNa'],
                                                     'color': (51, 255, 204),
                                                     },
                  'Fractional_excretion_of_urea': {'generic_term': [],
                                                   'spacific_term': ['fractional excretion of urea'],
                                                   'color': (51, 255, 204),
                                                   },
                  'Intravenous_fluids': {'generic_term': [],
                                         'spacific_term': ['intravenous fluids', 'IVF', 'normal saline', 'IV fluid bolus', 'IV fluid resusitation, hydration'],
                                         'color': (173, 206, 235),
                                         },
                  'KUB': {'generic_term': [],
                          'spacific_term': ['kidney, ureter, bladder scan', 'KUB scan', 'Kidney/Ureters/Bladder'],
                          'color': (255, 210, 77),
                          },
                  'Limit_exposure_to_contrast_media_radiation': {'generic_term': [],
                                                                        'spacific_term': ['Limit exposure to contrast media and/or radiation',
                                                                                          'Limit exposure to contrast media',
                                                                                          'Limit exposure to contrast agents'],
                                                                        'color': (173, 206, 235),
                                                                        },
                  'Renal_biopsy': {'generic_term': [],
                                   'spacific_term': ['renal biopsy', 'renal bx'],
                                   'color': (255, 210, 77),
                                   },
                  'Renal_computed_tomography': {'generic_term': [],
                                                'spacific_term': ['Renal Computed Tomography',
                                                                  'Renal CT', 'kidney CT', 'CT of the kidney'],
                                                'color': (255, 210, 77),
                                                },
                  'Renal_ultrasound': {'generic_term': [],
                                       'spacific_term': ['renal Ultrasound', 'US Renal', 'Renal US', 'US Kidney', 'Kidney US'],
                                       'color': (255, 210, 77),
                                       },
                  'Serum_creatinine ': {'generic_term': [],
                                        'spacific_term': ['serum creatinine', 'SCr', 'Cr', 'Creatinine', 'CREAT'],
                                        'color': (255, 210, 77),
                                        },
                  'Renal_Replacement_therapy': {'generic_term': ['RRT'],
                                                'spacific_term': ['Renal Replacement Therapy', 'Hemodialysis', 'Peritoneal dialysis', 'continuous venovenous hemodiafiltration',
                                                                  'HD', 'CVVHD'],
                                                'color': (173, 206, 235),
                                                },
                  'serum_cystatic_c': {'generic_term': [],
                                       'spacific_term': ['serum cystatic c'],
                                       'color': (173, 206, 235),
                                       },
                  'Serum_sodium': {'generic_term': [],
                                   'spacific_term': ['Serum Sodium', 'Serum Na', 'plasma sodium', 'plasma Na'],
                                   'color': (255, 210, 77),
                                   },
                  'Serum_urea': {'generic_term': [],
                                 'spacific_term': ['serum urea', 'plasma urea'],
                                 'color': (255, 210, 77),
                                 },
                  'Urine_creatinine': {'generic_term': [],
                                       'spacific_term': ['urine creatinine', 'UrCr', 'Urine Cr', 'creatinine,random urine', 'creat rndm u'],
                                       'color': (255, 210, 77),
                                       },
                  'Urine_dipstick': {'generic_term': [],
                                     'spacific_term': ['Urine dipstick',],
                                     'color': (255, 210, 77),
                                     },
                  'Urine_osmolality': {'generic_term': [],
                                       'spacific_term': ['Urine osmolality', 'osmol random u'],
                                       'color': (255, 210, 77),
                                       },
                  'Urine_protein': {'generic_term': [],
                                    'spacific_term': ['urine protein', 'Protein, UA', 'UA Protein', 'prot random u'],
                                    'color': (255, 210, 77),
                                    },
                  'Urine_sediment': {'generic_term': [],
                                     'spacific_term': ['urine sediment',],
                                     'color': (255, 210, 77),
                                     },
                  'Urine_sodium': {'generic_term': [],
                                   'spacific_term': ['urine sodium', 'sodium, urine 24 hour', 'urine sodium, random', 'sodium,random urine'],
                                   'color': (255, 210, 77),
                                   },
                  'Urine_specific_gravity': {'generic_term': [],
                                             'spacific_term': ['urine specific gravity', 'specific gravity, ua', 'spec grav', 'spec gravi',
                                                               'ua spgr',],
                                             'color': (255, 210, 77),
                                             },
                  'Urine_urea': {'generic_term': [],
                                 'spacific_term': ['urine urea'],
                                 'color': (255, 210, 77),
                                 },
                  'Urine_volume': {'generic_term': [],
                                   'spacific_term': ['urine volume', 'urine output', 'decreased urine output'],
                                   'color': (51, 255, 204),
                                   },
                  'Hemodialysis': {'generic_term': [],
                                   'spacific_term': ['Hemodialysis',],
                                   'color': (51, 255, 204),
                                   },


                  }
aki_attribute_regex_dict = {'Urine_volume':
                            r"\b(?:urine (?:output|volume)?\s?(?:goal)?)\b\s?(?:is|at|of|greater than|above|(?:\(!\))|>|<)?\s?:{0,2}?\s+(?:\(\d+\.?\d?\s?-\s?\d+\.?\d?\s?\)?|(?:\[.*?\])?)?\s?\b(\d+\.\d+|\d+)\s?(?:.*?)\s?([a-z]*\/?[a-z]*\/[a-z]*)?"}
aki_lab_list = ['urinalysis']

ami_attribute_dict = {
    'Acute_myocardial_infarction': {'generic_term': [],
                                    'spacific_term': ['Acute Myocardial Infarction', 'AMI', 'NSTEMI', 'non-ST elevation myocardial infarction', 'STEMI', 'ST elevation myocardial infarction', 'NQWMI', 'Non Q Wave Myocardial Infarction', 'AWMI', 'Anterior wall myocardial infarction'],
                                    'color': (128, 255, 128),

                                    },
    'Pain': {'generic_term': [],
             'spacific_term': ['chest pain', 'angina pectoris', 'squeezing pressure',
                               'heaviness in chest', 'burning pain in chest', 'pain in upper extremity',
                               'pain in mandibular', 'tight pain in jaw', 'crushing pain in jaw',
                               'epigastric pain', 'burning', 'stabbing'],
             'color': (172, 208, 149),
             },
    'Fatigue': {'generic_term': [],
                'spacific_term': ['extreme tiredness', 'weariness', 'exhaustion', 'Lethargy'],
                'color': (172, 208, 149),
                },
    'Insomnia': {'generic_term': [],
                 'spacific_term': ['Insomnia', 'habitual sleeplessness', 'inability to sleep', 'stay aslep'],
                 'color': (172, 208, 149),
                 },
    'Nausea': {'generic_term': [],
               'spacific_term': ['Nausea', 'N & V', 'nauseous', 'nausea and vomiting'],
               'color': (172, 208, 149),
               },
    'Heart_palpitations': {'generic_term': [],
                           'spacific_term': ['Heart palpitations', 'Heart pounding', 'flip-flop feeling', 'beating too fast', 'fluttering rapidly', 'skipping beats'],
                           'color': (172, 208, 149),
                           },
    'Anxiety': {'generic_term': [],
                'spacific_term': ['Anxious', 'Intense fear', 'Intense terror', 'prolonged nervousness', 'fearfullness'],
                'color': (172, 208, 149),
                },
    'Diaphoresis': {'generic_term': [],
                    'spacific_term': ['Diaphoresis', 'sweating', 'cold sweats', 'secondary hyperhidrosis'],
                    'color': (172, 208, 149),
                    },
    'Syncope': {'generic_term': [],
                'spacific_term': ['Syncope', 'Feeling lightheaded', 'dizzy', 'passing out', 'fainting', 'transient loss of consciousness'],
                'color': (172, 208, 149),
                },
    'Cardiac_troponin': {'generic_term': [],
                         'spacific_term': ['cardiac troponin I', 'CTnl', 'cardiac troponin T', 'CTnT', 'cardiac-specific troponin I', 'troponin T', 'cardiac troponin', 'troponin'],
                         'color': (255, 210, 77),
                         },
    'Creatine_kinase': {'generic_term': [],
                        'spacific_term': ['Creatine Kinase MB', 'CK-MB', 'Creatine Kinase', 'CKMB'],
                        'color': (255, 210, 77),
                        },
    'Percutaneous_coronary_artery_intervention': {'generic_term': [],
                                                  'spacific_term': ['Percutaneous coronary artery intervention', 'PCI',
                                                                    'Percutaneous Translumal Coronary Angioplasty', 'PTCA', 'Balloon Angioplasty', 'Stent (BMS or DES) Implantation', ' Stent (BMS or DES) Deployment', 'Coronary Atherectomy',  'Directional Coronary Atherectomy', 'Rotational Atherectomy', 'Laser Atherectomy',
                                                                    'Shockwave Lithotripsy/Lithoplasty', 'Lithoplasty/Lithotripsy'],
                                                  'color': (196, 255, 77),
                                                  },
    'Coronary_artery_bypass_graft': {'generic_term': [],
                                     'spacific_term': ['Coronary artery bypass grafting', 'Coronary artery bypass graft', 'CABG',],
                                     'color': (196, 255, 77),
                                     },
    'Fibrolytics': {'generic_term': [],
                    'spacific_term': ['Fibrolytics', 'Thrombolytics', 'thrombolytic agents', 'plasminogen activators', 'Streptokinase', 'Activase', 'Alteplase', 'Reteplase', 'Tenecteplase', 'TNK-tPA', 'TNKase', 'Urokinase', 'Prourokinase', 'Anistreplase', 'APSAC', 'Eminase', 'Anisoylated plasminogen streptokinase activator complex'],
                    'color': (173, 206, 235),
                    },
    'Antiplatelets': {'generic_term': [],
                      'spacific_term': ['Aspirin', 'Plavix', 'Clopidogrel', 'Effent', 'Prasugrel', 'Brilinta', 'Ticagrelor', 'Cangrelor', 'Glycoprotein', 'GP', 'IIb-IIIa',
                                        'adenosine diphosphate inhibitor', 'ADP', 'receptor inhibitor', 'P2Y12 inhibitor'],
                      'color': (173, 206, 235),
                      },
    'Antcoagulant': {'generic_term': [],
                     'spacific_term': ['Heparin', 'Coumadin', 'Warfarin', 'Eliquis', 'Apixaban', 'Pradaxa', 'Edoxaban', 'Xarelto', 'Rivaroxaban'],
                     'color': (173, 206, 235),
                     },
    'Beta-Blockers': {'generic_term': [],
                      'spacific_term': ['Beta-Blockers', 'beta blockers',
                                        'Acebutolol', 'Sectral', 'Atenolol', 'Tenormin', 'Betzolol', 'Kerlone', 'Bisoprolol', 'Zebeta', 'Ziac',
                                                      'Caretolol', 'Cartrol', 'Carvedilol', 'Coreg', 'Labetalol', 'Normodyne', 'Trandate', 'Metoprolol', 'Lopressor', 'Toprol',
                                                      'Nadolol', 'Corgard', 'Penbutolol', 'Levatol', 'Propranolol', 'Inderal', 'Inderal LA', 'Timolol', 'Blocadren'],
                      'color': (173, 206, 235),
                      },
    'ACE-Inhibitors': {'generic_term': [],
                       'spacific_term': ['ACE-Inhibitors', 'Angiotensin-converting enzyme', 'ACE', 'Lotensin', 'Benazepril', 'Capoten', 'Captopril', 'Vasotec', 'Enalapril', 'Prinivil', 'Lisinopril', 'Altace', 'Ramipril',
                                         'Perindopril', 'Aceon', 'Fosinopril', 'Monopril', 'Fosinopril', 'monopril'],
                       'color': (173, 206, 235),
                       },
    'Statins': {'generic_term': [],
                'spacific_term': ['Statins', 'Atorvastatin', 'Lipitor', 'Simvastatin', 'Zocor', 'Fluvastatin', 'Lescol XL',
                                  'Lovastatin', 'Altoprev', 'Pravastatin', 'Pravachol', 'Rosuvastatin', 'Crestor', 'Ezallor',
                                                'Pitavastatin', 'Livalo', 'Zypitamag', 'Atorvastatin-Amlodipine', 'Caudet', 'Ezetimibe-simvastatin', 'Vytorin'],
                'color': (173, 206, 235),
                },
    'Antianginals': {'generic_term': [],
                     'spacific_term': ['Antianginals', 'Amlodipine Besylate', 'Katerzia', 'Norvasc', 'Tenormin', 'Bisoprolol Fumarate',
                                       'Cardizem', 'Diltiazem HCL', 'Diltiazem HCL ER', 'Cartia XT ', 'Matzim LA', 'Tiazac',
                                       'Taxtia XT', 'Dipyridamol', 'Felodipine ER', 'Isosorbide Monontrate', 'Metoprolol Succinate ER',
                                       'Toprol XL', 'Metoprolol Tartrate', 'Lopressor',  'Nadolol', 'Corgard', 'Nifedipine', 'Nifedipine ER',
                                       'Procardia XS', 'Nifedipine ER', 'Sular', 'Nisoldpine', 'Nitroglycerin',
                                       'NoNitro', 'Nitroglycerin', 'Nitromist', 'Nitrostat', 'Verapamil HCL', 'Verapamil HCI ER'],
                     'color': (173, 206, 235),
                     },
    'Electrocardiograms': {'generic_term': [],
                           'spacific_term': ['Electrocardiograms', 'ST-Segment elevation', 'Abnormal Q-Wave', 'New LBBB', 'new left bundle branch block',
                                             'EKG', 'ECG'],
                           'color': (255, 210, 77),
                           },
    'Echocardiograms': {'generic_term': [],
                        'spacific_term': ['ECHO', 'TTE', 'transthoracic echocardiography', 'stress echocardiography', 'transesophageal echocardiograph', 'three-dimensional(3D) echocardiography',
                                          'echocardiography'],
                        'color': (255, 210, 77),
                        },
    'Radionuclide_imaging': {'generic_term': [],
                             'spacific_term': ['Radionuclide imaging', 'myocardial perfusion imaging', 'SPECT', 'Single photon emission computed tomography'],
                             'color': (255, 210, 77),
                             },
    'Computed_tomography_coronary_angiography': {'generic_term': [],
                                                 'spacific_term': ['Computed Tomography Coronary Angiography',
                                                                   'CCTA', 'cardiac CT angiography', 'CT coronary angiogram', 'coronary CT angiogram', 'coronary CT angiography',
                                                                   'Coronary Computed tomography angiography',],
                                                 'color': (255, 210, 77),
                                                 },
    'Cardiac_catheterization': {'generic_term': [],
                                'spacific_term': ['Cardiac Catheterization', 'Cardiac cath', 'Right heart cath', 'Left heart cath', 'Right and left heart cath'],
                                'color': (196, 255, 77),
                                },
    'Abnormal_ecg_or_ekg': {'generic_term': [],
                            'spacific_term': ['Abnormal ECG', 'Abnormal EKG'],
                            'color': (172, 208, 149),
                            },
    'Abnormal_echocardiogram': {'generic_term': [],
                                'spacific_term': ['Abnormal Echocardiogram', 'abnormal ECHO'],
                                'color': (172, 208, 149),
                                },
    'Angina': {'generic_term': [],
               'spacific_term': ['Angina pectoris', 'stable angina', 'unstable angina', 'variant angina',
                                 'aginal pain', 'Squeezing chest pain', 'constricting discomfort in front of chest',
                                 'Typical angina', 'atypical angina', 'vasospastic angina', ],
               'color': (172, 208, 149),
               },

}
ami_attribute_regex_dict = {}
ami_lab_list = ['trop_ckmb']

template_excerpt_data = {
    'pneumonia': {'attribute_dict':pneumonia_attribute_dict,
                  'attribute_regex_dict': pneumonia_attribute_regex_dict,
                  'lab_list': pneumonia_lab_list,
                  'attribute_list': list(pneumonia_attribute_dict.keys()-pneumonia_attribute_regex_dict.keys()-set(['CBC', 'CMP', 'Bands', 'Pneumonia']))},
                  
        
    'aki': {'attribute_dict': aki_attribute_dict,
            'attribute_regex_dict': aki_attribute_regex_dict,
            'lab_list': aki_lab_list,
            'attribute_list': list(aki_attribute_dict.keys()-aki_attribute_regex_dict.keys()-set(['Urine_creatinine', 'Urine_dipstick', 'Urine_osmolality', 'Urine_protein', 'Urine Sediment', 'Urine_sodium', 'Urine_specific_gravity', 'Urine_urea', 'Urine_volume']))},

    'ami': {'attribute_dict': ami_attribute_dict,
            'attribute_regex_dict': ami_attribute_regex_dict,
            'lab_list': ami_lab_list,
            'attribute_list': list(ami_attribute_dict.keys()-ami_attribute_regex_dict.keys()-set(['Creatine_kinase', 'Cardiac_troponin']))},
        
}