import re
import boto3
from datetime import datetime, date

s3_client = boto3.client('s3', region_name='us-east-1')
TIMEDELTA = 7
DOWNLOAD_BUCKET_NAME = 'zai-reference-data'
DEST_FOLDER_LEVEL_1 = 'zigna'
DEST_FOLDER_LEVEL_2 = 'policy_catalog'
DEST_FOLDER_LEVEL_4 = 'production_data'
DEST_FOLDER_LEVEL_5 =  date.today()
DEST_FOLDER_LEVEL_6 =  'extraction'
DEST_FOLDER_LEVEL_7 = 'batch'

all_states = ['Alabama','Nevada','Kentucky','North Mariana Islands','Kansas','Florida','Missouri','South Dakota',
        'Washington','Colorado','Puerto Rico','North Dakota','Nebraska','New Jersey','Maryland','Wyoming','Arkansas',
        'US Virgin Islands','California','Utah','Minnesota','Louisiana','Oregon','Delaware','Mississippi','Wisconsin','Montana','Arizona',
        'Iowa','South Carolina','Illinois','Connecticut','New Mexico','Texas','Tennessee','Pennsylvania','Maine','Alaska','District of Columbia',
        'American Samoa','Ohio','Rhode Island','Georgia','Indiana','Michigan','Idaho','Virginia','Hawaii','New Hampshire',
        'Guam','Oklahoma','Massachusetts','New York','Vermont','West Virginia','North Carolina']
marketplace_states_medical = ['Alabama', 'Arizona', 'Colorado', 'Florida', 'Georgia', 'Illinois', 'Kansas', 'Louisiana', 'Maryland', 'Michigan', 'Mississippi', 'Missouri', 
            'New Jersey', 'New Mexico', 'North Carolina', 'Ohio', 'Oklahoma', 'South Carolina','Tennessee', 'Texas', 'Virginia', 'Washington','Wisconsin']
marketplace_states_reimb = ['Alabama', 'Arizona', 'Florida', 'Georgia', 'Illinois', 'Kansas', 'Louisiana', 'Maryland', 'Massachusetts', 'Michigan', 'Mississippi', 'Missouri', 'New Jersey', 
            'New Mexico', 'New York', 'North Carolina', 'Ohio', 'Oklahoma', 'South Carolina','Tennessee', 'Texas', 'Virginia', 'Washington', 'Wisconsin']
medicaid_states = ['Alabama','Nevada','North Mariana Islands','Kansas','Florida','Missouri','South Dakota','Washington','Colorado',
            'Puerto Rico','North Dakota','Nebraska','New Jersey','Maryland','Wyoming','Arkansas','US Virgin Islands','California',
            'Utah','Minnesota','Oregon','Delaware','Wisconsin','Montana','Arizona','Iowa','South Carolina','Illinois','Connecticut',
            'Texas','Maine','Alaska','District of Columbia','American Samoa','Rhode Island','Georgia','Michigan','Idaho','Virginia',
            'Hawaii','New Hampshire','Guam','Oklahoma','Massachusetts','New York','Vermont','West Virginia']
medicaid_reimb = ['Alabama','Nevada','Kentucky','North Mariana Islands','Kansas','Florida','Missouri','South Dakota','Washington',
            'Colorado','Puerto Rico','North Dakota','Nebraska','New Jersey','Maryland','Wyoming','Arkansas','US Virgin Islands',
            'California','Utah','Minnesota','Oregon','Delaware','Mississippi','Wisconsin','Montana','Arizona','Iowa','South Carolina',
            'Illinois','Connecticut','Texas','New Mexico', 'Tennessee','Pennsylvania','Maine','Alaska','District of Columbia','American Samoa',
            'Ohio','Rhode Island','Georgia','Indiana','Michigan','Idaho','Virginia','Hawaii','New Hampshire','Guam','Oklahoma','Massachusetts',
            'New York','Vermont','West Virginia','North Carolina']
oxford_states = ['Connecticut', 'New Jersey', 'New York']
west_states =  ['Arizona', 'California', 'Colorado', 'Oklahoma', 'Oregon', 'Texas', 'Utah', 'Washington']
surest_states = ['Alabama', 'Arizona', 'Arkansas', 'Colorado', 'Delaware', 'District of Columbia',
                'Florida', 'Georgia', 'Illinois', 'Indiana', 'Kansas', 'Kentucky', 'Louisiana',
                'Michigan', 'Minnesota', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 
                'New Hampshire', 'North Carolina', 'Ohio', 'Oklahoma', 'Pennsylvania', 
                'Rhode Island', 'South Carolina', 'Tennessee', 'Texas', 'Utah', 'Virginia', 
                'West Virginia', 'Wyoming']
heritage_states = ['Arkansas', 'Georgia', 'Illinois', 'Iowa', 'Louisiana','North Carolina', 'Ohio', 'South Carolina', 'Tennessee', 'Virginia']
midatlantic_states = ["District of Columbia", "Maryland", "Pennsylvania", "Virginia", "West Virginia"]
md_ipa_states = ["District of Columbia", "Maryland", "Pennsylvania", "Virginia", "West Virginia"]
optimum_states = ["District of Columbia", "Maryland", "Pennsylvania", "Virginia", "West Virginia"]

nevada_sample = {
         "Rocky Mountain Health Plan":{
                        "https://www.rmhp.org/medical-policies/": {"lob": ['Marketplace', 'Medicare Advantage', 'Medicaid'], "state": ['Colorado']}
                       }
        }


uhc_base_urls = {"":{
                        "https://www.uhcprovider.com/en/policies-protocols/commercial-policies/commercial-medical-drug-policies.html": {"lob": "Commercial", "state": all_states},
                        "https://www.uhcprovider.com/en/policies-protocols/commercial-policies/commercial-reimbursement-policies.html": {"lob": "Commercial", "state": all_states},
                        "https://www.uhcprovider.com/en/policies-protocols/exchange-policies/exchanges-medical-drug-policies.html": {"lob": "Marketplace", "state": marketplace_states_medical},
                        "https://www.uhcprovider.com/en/policies-protocols/exchange-policies/exchanges-reimbursement-policies.html": {"lob": "Marketplace", "state": marketplace_states_reimb},
                        "https://www.uhcprovider.com/en/policies-protocols/medicare-advantage-policies/medicare-advantage-medical-policies.html": {"lob": "Medicare Advantage", "state": all_states},
                        "https://www.uhcprovider.com/en/policies-protocols/medicare-advantage-policies/medicare-advantage-reimbursement-policies.html": {"lob": "Medicare Advantage", "state": all_states},
                        "https://www.uhcprovider.com/en/policies-protocols/comm-plan-medicaid-policies/medicaid-community-state-policies.html": {"lob": "Medicaid", "state": medicaid_states},
                        "https://www.uhcprovider.com/en/policies-protocols/comm-plan-medicaid-policies/reimbursement-community-state-policies.html": {"lob": "Medicaid", "state": medicaid_reimb},
                        "https://www.uhcprovider.com/en/policies-protocols/clinical-guidelines.html": {"lob": "", "state": all_states}
                       },
                
                "Oxford Health Plan":{
                        "https://www.uhcprovider.com/en/policies-protocols/commercial-policies/oxford-policies.html": {"lob":['Commercial', 'Marketplace'], "state": oxford_states},
                        "https://www.uhcprovider.com/en/policies-protocols/commercial-policies/commercial-medical-drug-policies.html": {"lob":['Commercial', 'Marketplace'], "state": oxford_states},
                        "https://www.uhcprovider.com/en/policies-protocols/commercial-policies/commercial-reimbursement-policies.html": {"lob":['Commercial', 'Marketplace'], "state": oxford_states}
                       },
                
                "UHC West Benefit":{
                        "https://www.uhcprovider.com/en/policies-protocols/commercial-policies/sv-benefit-interpretation-policies.html": {"lob": "Commercial", "state": west_states}
                       },

                "UHC West Medical":{
                        "https://www.uhcprovider.com/en/policies-protocols/commercial-policies/sv-medical-mgmt-guidelines.html": {"lob": "Commercial", "state": west_states}
                       },

                "UMR":{
                        "https://www.uhcprovider.com/en/policies-protocols/commercial-policies/umr-medical-drug-policies.html": {"lob": "Commercial", "state": all_states}
                       },

                "Government Employees Health Association (GEHA)":{
                        "https://www.geha.com/resource-center/provider-resources?cat=Providers&tag=Coverage%20Policies": {"lob": ["Commercial", "Medicare Advantage"], "state": all_states},
                        "https://www.uhcprovider.com/en/policies-protocols/commercial-policies/commercial-medical-drug-policies.html": {"lob": "Commercial", "state": all_states},
                        "https://www.uhcprovider.com/en/policies-protocols/medicare-advantage-policies/medicare-advantage-medical-policies.html": {"lob": "Medicare Advantage", "state": all_states},
                        "https://www.uhcprovider.com/en/policies-protocols/medicare-advantage-policies/medicare-advantage-reimbursement-policies.html": {"lob":"Medicare Advantage", "state":all_states}
                       },

                "The Empire Plan":{
                        "https://www.uhcprovider.com/en/policies-protocols/commercial-policies/commercial-medical-drug-policies.html": {"lob": "Commercial", "state": ['New York']},
                        "https://www.uhcprovider.com/en/policies-protocols/commercial-policies/commercial-reimbursement-policies.html": {"lob": "Commercial", "state": ['New York']}
                       },

                "United Healthcare of Nevada":{
                        "https://healthplanofnevada.com/provider/medical-policies": {"lob": "Marketplace", "state": ['Nevada']}
                       },

                "Rocky Mountain Health Plan":{
                        "https://www.uhcprovider.com/en/policies-protocols/exchange-policies/exchanges-reimbursement-policies.html": {"lob": "Marketplace", "state": ['Colorado']},
                        "https://www.uhcprovider.com/en/health-plans-by-state/colorado-health-plans/co-comm-plan-home/co-cp-policies/reimbursement-community-state-policies-colorado.html": {"lob": "Medicaid", "state": ['Colorado']},
                        "https://www.rmhp.org/medical-policies/": {"lob": ['Marketplace', 'Medicare Advantage', 'Medicaid'], "state": ['Colorado']},
                        "https://www.uhcprovider.com/en/policies-protocols/medicare-advantage-policies/medicare-advantage-medical-policies.html":{"lob": 'Medicare Advantage', "state": ['Colorado']},
                        "https://www.uhcprovider.com/en/policies-protocols/medicare-advantage-policies/medicare-advantage-reimbursement-policies.html":{"lob": 'Medicare Advantage', "state": ['Colorado']}
                       },

                "UHC Community Plan of Indiana":{
                        "https://www.uhcprovider.com/en/health-plans-by-state/indiana-health-plans/in-comm-plan-home/in-cp-policies/medicaid-community-state-policies-in.html": {"lob": "Medicaid", "state": ['Indiana']}
                       },

                "UHC Community Plan of Kentucky":{
                        "https://www.uhcprovider.com/en/health-plans-by-state/kentucky-health-plans/ky-comm-plan-home/ky-cp-policies/medicaid-community-state-policies-ky.html": {"lob": "Medicaid", "state": ['Kentucky']}
                       },

                "UHC Community Plan of Louisiana":{
                        "https://www.uhcprovider.com/en/health-plans-by-state/louisiana-health-plans/la-comm-plan-home/la-cp-policies/medicaid-community-state-policies-la.html": {"lob": "Medicaid", "state": ['Louisiana']},
                        "https://www.uhcprovider.com/en/health-plans-by-state/louisiana-health-plans/la-comm-plan-home/la-cp-policies/reimbursement-community-state-policies-louisiana.html": {"lob": "Medicaid", "state": ['Louisiana']}
                       },

                "UHC Community Plan of Mississippi":{
                        "https://www.uhcprovider.com/en/health-plans-by-state/mississippi-health-plans/ms-comm-plan-home/ms-cp-policies/medicaid-community-state-policies-ms.html": {"lob": "Medicaid", "state": ['Mississippi']}
                       },

                "UHC Community Plan of North Carolina":{
                        "https://www.uhcprovider.com/en/health-plans-by-state/north-carolina-health-plans/nc-comm-plan-home/nc-cp-policies/nc-medicaid-community-state-policies.html": {"lob": "Medicaid", "state": ['North Carolina']}
                       },

                "UHC Community Plan of Ohio":{
                        "https://www.uhcprovider.com/en/health-plans-by-state/ohio-health-plans/oh-comm-plan-home/oh-cp-policies/medicaid-community-state-policies-oh.html": {"lob": "Medicaid", "state": ['Ohio']}
                       },

                "UHC Community Plan of Pennsylvania":{
                        "https://www.uhcprovider.com/en/health-plans-by-state/pennsylvania-health-plans/pa-comm-plan-home/pa-cp-policies/medicaid-community-state-policies-pa.html": {"lob": "Medicaid", "state": ['Pennsylvania']}
                       },

                "UHC Community Plan of Tennessee":{
                        "https://www.uhcprovider.com/en/health-plans-by-state/tennessee-health-plans/tn-comm-plan-home/tn-cp-policies/medicaid-community-state-policies-tn.html": {"lob": "Medicaid", "state": ['Tennessee']}
                       },

                "UHC Community Plan of New Mexico":{
                        "https://www.uhcprovider.com/en/health-plans-by-state/new-mexico-health-plans/nm-comm-plan-home/nm-cp-policies/medicaid-community-state-policies-nm.html": {"lob": "Medicaid", "state": ['New Mexico']}
                       },

                "All Savers Health Plan":{
                        "https://www.uhcprovider.com/en/policies-protocols/commercial-policies/commercial-medical-drug-policies.html": {"lob": "Commercial", "state": all_states},
                        "https://www.uhcprovider.com/en/policies-protocols/commercial-policies/commercial-reimbursement-policies.html": {"lob": "Commercial", "state": all_states}
                       },

                "Surest":{
                        "https://www.uhcprovider.com/en/policies-protocols/commercial-policies/commercial-medical-drug-policies.html": {"lob": "Commercial", "state": surest_states},
                        "https://www.uhcprovider.com/en/policies-protocols/commercial-policies/commercial-reimbursement-policies.html": {"lob": "Commercial", "state": surest_states}
                       },

                "Heritage/UHC of the River Valley":{
                        "https://www.uhcprovider.com/en/policies-protocols/commercial-policies/commercial-medical-drug-policies.html": {"lob": "Commercial", "state": heritage_states},
                        "https://www.uhcprovider.com/en/policies-protocols/commercial-policies/commercial-reimbursement-policies.html": {"lob": "Commercial", "state": heritage_states}
                       },

                "Mid-Atlantic Health Plan":{
                        "https://www.uhcprovider.com/en/policies-protocols/commercial-policies/commercial-medical-drug-policies.html": {"lob": "Commercial", "state": midatlantic_states},
                        "https://www.uhcprovider.com/en/policies-protocols/commercial-policies/commercial-reimbursement-policies.html": {"lob": "Commercial", "state": midatlantic_states}
                       },

                "UHC MD IPA Plan":{
                        "https://www.uhcprovider.com/en/policies-protocols/commercial-policies/commercial-medical-drug-policies.html": {"lob": "Commercial", "state": md_ipa_states},
                        "https://www.uhcprovider.com/en/policies-protocols/commercial-policies/commercial-reimbursement-policies.html": {"lob": "Commercial", "state": md_ipa_states}
                       },

                "Optimum Choice":{
                        "https://www.uhcprovider.com/en/policies-protocols/commercial-policies/commercial-medical-drug-policies.html": {"lob": "Commercial", "state": optimum_states},
                        "https://www.uhcprovider.com/en/policies-protocols/commercial-policies/commercial-reimbursement-policies.html": {"lob": "Commercial", "state": optimum_states}
                       }
                    }

centene_dict_new = {'absolute total care': ['https://www.absolutetotalcare.com/providers/resources/payment-policies.html',
  'https://www.absolutetotalcare.com/providers/resources/clinical-payment-policies.html',
  'https://www.absolutetotalcare.com/providers/quality-improvement/practice-guidelines.html'],
 'absolute total care / healthy connections': ['https://www.absolutetotalcare.com/providers/resources/behavioral-health-clinical-policies.html'],
 'ambetter by fidelis care': ['https://www.fideliscare.org/Provider/Provider-Policies'],
 'ambetter by peach state health plan': ['https://ambetter.pshpgeorgia.com/provider-resources/clinical-payment-policies.html'],
 'ambetter by sunshine health': ['https://ambetter.sunshinehealth.com/provider-resources/clinical-payment-policies.html'],
 'ambetter from absolute total care': ['https://ambetter.absolutetotalcare.com/provider-resources/clinical-payment-policies.html'],
 'ambetter from arizona complete health': ['https://ambetter.azcompletehealth.com/provider-resources/clinical-payment-policies.html'],
 'ambetter from arkansas health & wellness': ['https://ambetter.arhealthwellness.com/provider-resources/clinical-payment-policies.html'],
 'ambetter from buckeye health plan': ['https://ambetter.buckeyehealthplan.com/provider-resources/clinical-payment-policies.html'],
 'ambetter from coordinated care': ['https://ambetter.coordinatedcarehealth.com/provider-resources/clinical-payment-policies.html',
  'https://ambetter.coordinatedcarehealth.com/provider-resources/manuals-and-forms.html'],
 'ambetter from health net': ['https://www.healthnet.com/en_us/providers/working-with-hn/payment-policies.html'],
 'ambetter from home state health': ['https://www.homestatehealth.com/providers/tools-resources/clinical-payment-policies.html'],
 'ambetter from magnolia health': ['https://ambetter.magnoliahealthplan.com/provider-resources/clinical-payment-policies.html'],
 'ambetter from meridian': ['https://www.ambettermeridian.com/provider-resources/clinical-payment-policies.html'],
 'ambetter from mhs': ['https://ambetter.mhsindiana.com/provider-resources/clinical-payment-policies.html'],
 'ambetter from nebraska total care': ['https://ambetter.nebraskatotalcare.com/provider-resources/clinical-payment-policies.html'],
 'ambetter from nh healthy families': ['https://ambetter.nhhealthyfamilies.com/provider-resources/clinical-payment-policies.html'],
 'ambetter from pa health & wellness': ['https://ambetter.pahealthwellness.com/provider-resources/clinical-payment-policies.html'],
 'ambetter from silver summit health plan': ['https://ambetter.silversummithealthplan.com/provider-resources/clinical-payment-policies.html'],
 'ambetter from sunflower health plan': ['https://ambetter.sunflowerhealthplan.com/provider-resources/clinical-payment-policies.html'],
 'ambetter from superior healthplan': ['https://www.superiorhealthplan.com/providers/resources/clinical-payment-policies.html'],
 'ambetter from wellcare of new jersey': ['https://ambetter.wellcarenewjersey.com/provider-resources/clinical-payment-policies.html'],
 'ambetter from western sky community care': ['https://ambetter.westernskycommunitycare.com/provider-resources/clinical-payment-policies.html'],
 'ambetter of alabama': ['https://www.ambetterofalabama.com/provider-resources/clinical-payment-policies.html'],
 'ambetter of delaware': ['https://www.ambetterhealth.com/en/de/provider-resources/clinical-payment-policies/'],
 'ambetter of illinois': ['https://www.ambetterofillinois.com/provider-resources/clinical-payment-policies.html'],
 'ambetter of louisiana healthcare connections': ['https://ambetter.louisianahealthconnect.com/provider-resources/clinical-payment-policies.htm'],
 'ambetter of north carolina': ['https://www.ambetterofnorthcarolina.com/provider-resources/clinical-payment-policies.html'],
 'ambetter of oklahoma': ['https://www.ambetterofoklahoma.com/provider-resources/clinical-payment-policies.html'],
 'ambetter of tennessee': ['https://www.ambetteroftennessee.com/provider-resources/clinical-payment-policies.html'],
 'ambetter of wellcare kentucky': ['https://ambetter.wellcareky.com/provider-resources/clinical-payment-policies.html'],
 'arizona complete health-complete care plan': ['https://www.azcompletehealth.com/providers/resources/clinical-payment-policies.html'],
 'arkansas total care': ['https://www.arkansastotalcare.com/providers/resources/clinical-payment-policies.html'],
 'buckeye health plan': ['https://www.buckeyehealthplan.com/providers/resources/clinical-payment-policies.html',
  'https://www.buckeyehealthplan.com/providers/quality-improvement/practice-guidelines.html'],
 'buckeye health plan – mycare ohio': ['https://www.buckeyehealthplan.com/providers/resources/clinical-payment-policies.html',
  'https://www.buckeyehealthplan.com/providers/quality-improvement/practice-guidelines.html'],
 'care1st health plan arizona': ['https://www.care1staz.com/providers/resources/practice-guidelines1.html'],
 'carolina complete health': ['https://network.carolinacompletehealth.com/resources/clinical-policies.html',
  'https://network.carolinacompletehealth.com/resources/payment-policies.html'],
 "children's medical services health plan (kidcare)": ['https://www.sunshinehealth.com/providers/utilization-management/clinical-payment-policies.html'],
 'coordinated care': ['https://www.coordinatedcarehealth.com/providers/resources/clinical-payment-policies.html',
  'https://www.coordinatedcarehealth.com/providers/quality-improvement/practice-guidelines.html'],
 'delaware first health': ['https://www.delawarefirsthealth.com/providers/resources/clinical-payment-policies.html'],
 'fidelis care': ['https://www.fideliscarenj.com/providers/medicaid/claims/payment-policy.html',
  'https://www.fideliscarenj.com/providers/tools/clinical-guidelines.html',
  'https://www.wellcare.com/New%20Jersey/providers/clinical-guidelines/ccg-list',
  'https://www.fideliscare.org/Provider/Provider-Policies'],
 'health net': ['https://www.healthnet.com/content/healthnet/en_us/providers/working-with-hn/medical_policies.html',
  'https://www.healthnet.com/en_us/providers/working-with-hn/payment-policies.html'],
 'health net - calviva health': ['https://www.healthnet.com/en_us/providers/working-with-hn/payment-policies.html'],
 'health net - imperial valley': ['https://www.healthnet.com/en_us/providers/working-with-hn/payment-policies.html'],
 'health net health plan of oregon': ['https://www.healthnetoregon.com/for-providers/resources/clinical-payment-policies.html',
  'https://www.healthnetoregon.com/for-providers/resources/CPG.html'],
 'home state health': ['https://www.homestatehealth.com/providers/tools-resources/clinical-payment-policies.html'],
 'iowa total care': ['https://www.iowatotalcare.com/providers/resources/clinical-payment-policies.html'],
 'louisiana healthcare connections': ['https://www.louisianahealthconnect.com/providers/resources/clinical-payment-policies.html'],
 'magnolia health': ['https://www.magnoliahealthplan.com/providers/resources/clinical-payment-policies.html'],
 'meridian': ['https://www.ilmeridian.com/providers/resources/clinical-payment-policies.html',
  'https://www.mimeridian.com/providers/resources/medical-policies.html'],
 'meridiancomplete': ['https://mmp.mimeridian.com/provider/provider-tools-resources/medical-policies.html'],
 'mhn': ['https://www.mhn.com/providers/working-with-mhn/clinical-operations-practices/utilization-management/clinical-practice-guidelines.html'],
 'mhs health wisconsin (mhswi)': ['https://www.mhswi.com/providers/resources/clinical-payment-policies.html'],
 'mhs healthy indiana plan': ['https://www.mhsindiana.com/providers/clinical-payment-policies.html'],
 'nebraska total care': ['https://www.nebraskatotalcare.com/providers/resources/clinical-payment-policies.html'],
 'nh healthy families': ['https://www.nhhealthyfamilies.com/providers/resources/clinical-payment-policies.html'],
 'ohana health plan': ['https://www.ohanahealthplan.com/providers/tools/clinical-guidelines.html',
  'https://www.ohanahealthplan.com/providers/medicaid/claims/payment-policy.html',
  'https://www.ohanahealthplan.com/providers/medicaid/claims/payment-policy.html'],
 'oklahoma complete health': ['https://www.oklahomacompletehealth.com/providers/resources/clinical-payment-policies.html'],
 'pa health & wellness': ['https://www.pahealthwellness.com/providers/resources/clinical-payment-policies.html',
  'https://www.pahealthwellness.com/providers/quality-improvement/practice-guidelines.html'],
 'peach state health plan': ['https://www.pshpgeorgia.com/providers/resources/clinical-payment-policies.html'],
 'qual choice': ['https://documents.qualchoice.com/area/shared/medicalpolicies.aspx?ShowLinks=1'],
 'silver summit health plan': ['https://www.silversummithealthplan.com/providers/resources/COPY_clinical-payment-policies.html'],
 'sunflower health plan': ['https://www.sunflowerhealthplan.com/providers/resources/clinical-payment-policies.html'],
 'superior healthplan': ['https://www.superiorhealthplan.com/providers/resources/clinical-payment-policies.html'],
 'sushine health': ['https://www.sunshinehealth.com/providers/utilization-management/clinical-payment-policies.html'],
 'trillium community health plan': ['https://www.trilliumohp.com/providers/resources/clinical-payment-policies2.html',
  'https://www.trilliumohp.com/providers/resources/CPG.html'],
 'wellcare': ['https://www.wellcare.com/alabama/providers/medicare/claims',
  'https://www.wellcare.com/alabama/providers/clinical-guidelines',
  'https://www.wellcare.com/arizona/providers/medicare/claims',
  'https://www.wellcare.com/arizona/providers/clinical-guidelines',
  'https://www.wellcare.com/Arizona/providers/clinical-guidelines/ccg-list',
  'https://www.wellcare.com/arkansas/providers/medicare/claims',
  'https://www.wellcare.com/arkansas/providers/clinical-guidelines',
  'https://www.wellcare.com/Arkansas/providers/clinical-guidelines/ccg-list',
  'https://www.wellcare.com/california/providers/medicare/claims',
  'https://www.wellcare.com/California/providers/clinical-guidelines/ccg-list',
  'https://www.wellcare.com/california/providers/clinical-guidelines',
  'https://www.wellcare.com/connecticut/providers/medicare/claims/payment-policy',
  'https://www.wellcare.com/connecticut/providers/clinical-guidelines',
  'https://www.wellcare.com/Connecticut/providers/clinical-guidelines/ccg-list',
  'https://www.wellcarede.com/for-providers/clinical-payment-policies.html',
  'https://www.wellcare.com/florida/providers/medicare/claims',
  'https://www.wellcareca.com/medicare-pa-clinical-policies.html',
  'https://www.wellcare.com/florida/providers/clinical-guidelines/ccg-list',
  'https://www.wellcare.com/florida/providers/clinical-guidelines',
  'https://www.wellcare.com/georgia/providers/medicare/claims',
  'https://www.wellcare.com/georgia/providers/clinical-guidelines/ccg-list',
  'https://www.wellcare.com/georgia/providers/clinical-guidelines',
  'https://www.wellcare.com/illinois/providers/medicare/claims',
  'https://www.wellcare.com/illinois/providers/clinical-guidelines',
  'https://www.wellcare.com/indiana/providers/medicare/claims',
  'https://www.wellcare.com/indiana/providers/clinical-guidelines',
  'https://www.wellcare.com/kentucky/providers/medicare/claims',
  'https://www.wellcare.com/kentucky/providers/clinical-guidelines',
  'https://www.wellcare.com/en/louisiana/providers/medicare/claims',
  'https://www.wellcare.com/louisiana/providers/clinical-guidelines',
  'https://www.wellcare.com/maine/providers/clinical-guidelines',
  'https://www.wellcare.com/maine/providers/medicare/claims',
  'https://www.wellcare.com/massachusetts/providers/medicare/claims',
  'https://www.wellcare.com/massachusetts/providers/clinical-guidelines',
  'https://www.wellcare.com/mississippi/providers/medicare/claims',
  'https://www.wellcare.com/mississippi/providers/clinical-guidelines',
  'https://www.wellcare.com/missouri/providers/medicare/claims',
  'https://www.wellcare.com/missouri/providers/clinical-guidelines',
  'https://www.wellcarene.com/for-providers.html',
  'https://www.silversummithealthplan.com/providers/resources/COPY_clinical-payment-policies.html',
  'https://www.wellcare.com/new-hampshire/providers/medicare/claims',
  'https://www.wellcare.com/new-hampshire/providers/clinical-guidelines',
  'https://www.wellcare.com/new-jersey/providers/medicare/claims',
  'https://www.wellcare.com/new-jersey/providers/clinical-guidelines',
  'https://www.wellcareca.com/medicare-pa-clinical-policies.html',
  'https://www.wellcare.com/north-carolina/providers/medicare/claims',
  'https://www.wellcare.com/north-carolina/providers/clinical-guidelines',
  'https://www.wellcare.com/ohio/providers/medicare/claims',
  'https://www.wellcare.com/ohio/providers/clinical-guidelines',
  'https://www.wellcareca.com/medicare-pa-clinical-policies.html',
  'https://www.wellcare.com/en/ohio/providers/medicare/claims/payment-policy',
  'https://www.wellcareok.com/for-providers/clinical-payment-policies.html',
  'https://www.pahealthwellness.com/providers/resources/clinical-payment-policies.html',
  'https://www.wellcare.com/rhode-island/providers/medicare/claims',
  'https://www.wellcare.com/rhode-island/providers/clinical-guidelines',
  'https://www.absolutetotalcare.com/providers/resources/payment-policies.html',
  'https://www.absolutetotalcare.com/providers/resources/clinical-payment-policies.html',
  'https://www.absolutetotalcare.com/providers/resources/behavioral-health-clinical-policies.html',
  'https://www.absolutetotalcare.com/providers/quality-improvement/practice-guidelines.html',
  'https://www.wellcare.com/tennessee/providers/medicare/claims',
  'https://www.wellcare.com/tennessee/providers/clinical-guidelines',
  'https://www.wellcare.com/texas/providers/clinical-guidelines/cpgs',
  'https://www.wellcare.com/texas/providers/medicare/claims',
  'https://www.wellcare.com/vermont/providers/medicare/claims',
  'https://www.wellcare.com/vermont/providers/clinical-guidelines',
  'https://www.wellcare.com/washington/providers/medicare/claims',
  'https://www.wellcare.com/washington/providers/clinical-guidelines',
  'https://www.mhswi.com/providers/resources/clinical-payment-policies.html',
  'https://www.wellcare.com/Illinois/providers/clinical-guidelines/ccg-list',
  'https://www.wellcare.com/Indiana/providers/clinical-guidelines/ccg-list',
  'https://www.wellcare.com/Louisiana/providers/clinical-guidelines/ccg-list',
  'https://www.wellcare.com/Maine/providers/clinical-guidelines/ccg-list',
  'https://www.wellcare.com/Massachusetts/providers/clinical-guidelines/ccg-list',
  'https://www.wellcareca.com/medicare-pa-clinical-policies.html',
  'https://www.wellcare.com/michigan/providers/medicare/claims',
  'https://www.wellcare.com/en/michigan/providers/medicare/claims/payment-policy',
  'https://www.wellcare.com/michigan/providers/clinical-guidelines',
  'https://www.wellcare.com/Michigan/providers/clinical-guidelines/ccg-list',
  'https://www.wellcare.com/Mississippi/providers/clinical-guidelines/ccg-list',
  'https://www.wellcare.com/Missouri/providers/clinical-guidelines/ccg-list',
  'https://www.wellcare.com/New%20Hampshire/providers/clinical-guidelines/ccg-list',
  'https://www.wellcare.com/New%20York/providers/clinical-guidelines/ccg-list',
  'https://www.wellcareca.com/medicare-pa-clinical-policies.html',
  'https://www.wellcare.com/North%20Carolina/providers/clinical-guidelines/ccg-list',
  'https://www.wellcare.com/Ohio/providers/clinical-guidelines/ccg-list',
  'https://www.wellcare.com/Rhode%20Island/providers/clinical-guidelines/ccg-list',
  'https://www.wellcare.com/South%20Carolina/providers/clinical-guidelines/ccg-list',
  'https://www.wellcare.com/Tennessee/providers/clinical-guidelines/ccg-list',
  'https://www.wellcare.com/texas/providers/clinical-guidelines/ccg-list',
  'https://www.wellcare.com/Vermont/providers/clinical-guidelines/ccg-list',
  'https://www.wellcare.com/Washington/providers/clinical-guidelines/ccg-list',
  'https://www.wellcareca.com/medicare-pa-clinical-policies.html',
  'https://www.wellcareca.com/medicare-pa-clinical-policies.html',
  'https://www.wellcareca.com/medicare-pa-clinical-policies.html',
  'https://www.wellcareca.com/medicare-pa-clinical-policies.html',
  'https://www.wellcareca.com/medicare-pa-clinical-policies.html',
  'https://www.wellcareca.com/medicare-pa-clinical-policies.html',
  'https://www.wellcareca.com/medicare-pa-clinical-policies.html',
  'https://www.wellcareca.com/medicare-pa-clinical-policies.html',
  'https://www.wellcareca.com/medicare-pa-clinical-policies.html',
  'https://www.wellcareca.com/medicare-pa-clinical-policies.html',
  'https://www.wellcareca.com/medicare-pa-clinical-policies.html',
  'https://www.wellcareca.com/medicare-pa-clinical-policies.html',
  'https://www.wellcareca.com/medicare-pa-clinical-policies.html',
  'https://www.wellcareca.com/medicare-pa-clinical-policies.html',
  'https://www.wellcareca.com/medicare-pa-clinical-policies.html',
  'https://www.wellcareca.com/medicare-pa-clinical-policies.html',
  'https://www.wellcareca.com/medicare-pa-clinical-policies.html',
  'https://www.wellcareca.com/medicare-pa-clinical-policies.html',
  'https://www.wellcareca.com/medicare-pa-clinical-policies.html',
  'https://www.wellcareca.com/medicare-pa-clinical-policies.html',
  'https://www.wellcare.com/en/alabama/providers/medicare/claims/payment-policy',
  'https://www.wellcare.com/en/arizona/providers/medicare/claims/payment-policy',
  'https://www.wellcare.com/en/arkansas/providers/medicare/claims/payment-policy',
  'https://www.wellcare.com/en/california/providers/medicare/claims/payment-policy',
  'https://www.wellcare.com/en/connecticut/providers/medicare/claims/payment-policy',
  'https://www.wellcare.com/en/florida/providers/medicare/claims/payment-policy',
  'https://www.wellcare.com/en/georgia/providers/medicare/claims/payment-policy',
  'https://www.wellcare.com/en/illinois/providers/medicare/claims/payment-policy',
  'https://www.wellcare.com/en/indiana/providers/medicare/claims/payment-policy',
  'https://www.wellcare.com/en/kentucky/providers/medicare/claims/payment-policy',
  'https://www.wellcare.com/en/louisiana/providers/medicare/claims/payment-policy',
  'https://www.wellcare.com/en/maine/providers/medicare/claims/payment-policy',
  'https://www.wellcare.com/en/Massachusetts/providers/medicare/claims/payment-policy',
  'https://www.wellcare.com/en/mississippi/providers/medicare/claims/payment-policy',
  'https://www.wellcare.com/en/missouri/providers/medicare/claims/payment-policy',
  'https://www.wellcare.com/en/new-hampshire/providers/medicare/claims/payment-policy',
  'https://www.wellcare.com/new-jersey/providers/medicare/claims/payment-policy',
  'https://www.wellcare.com/en/north-carolina/providers/medicare/claims/payment-policy',
  'https://www.wellcare.com/en/rhode-island/providers/medicare/claims/payment-policy',
  'https://www.wellcare.com/en/tennessee/providers/medicare/claims/payment-policy',
  'https://www.wellcare.com/en/texas/providers/medicare/claims/payment-policy',
  'https://www.wellcare.com/en/vermont/providers/medicare/claims/payment-policy',
  'https://www.wellcare.com/en/washington/providers/medicare/claims/payment-policy',
  'https://www.wellcare.com/new-york/providers/clinical-guidelines',
  'https://www.wellcare.com/new-york/providers/medicare/claims',
  'https://www.wellcareca.com/medicare-pa-clinical-policies.html',
  'https://www.wellcare.com/new-york/providers/medicare/claims/payment-policy',
  'https://www.wellcareca.com/medicare-pa-clinical-policies.html'],
 'wellcare by allwell': ['https://www.wellcarecomplete.com/providers/payment-policies.html',
  'https://www.wellcarecomplete.com/providers/payment-policies.html',
  'https://www.wellcarecomplete.com/providers/payment-policies.html',
  'https://www.wellcarecomplete.com/providers/payment-policies.html',
  'https://www.wellcarecomplete.com/providers/payment-policies.html',
  'https://www.wellcarecomplete.com/providers/payment-policies.html',
  'https://www.wellcarecomplete.com/providers/payment-policies.html'],
 'wellcare by fidelis care': ['https://www.fideliscare.org/Provider/Provider-Policies'],
 'wellcare by health net': ['https://www.healthnet.com/en_us/providers/working-with-hn/payment-policies.html'],
 'wellcare by healthnet': ['https://www.healthnetoregon.com/for-providers/resources/clinical-payment-policies.html'],
 'wellcare by ohana health plan': ['https://www.wellcare.com/en/hawaii/providers/medicare/claims',
  'https://www.wellcare.com/hawaii/providers/clinical-guidelines',
  'https://www.wellcare.com/Hawaii/providers/clinical-guidelines/ccg-list',
  'https://www.wellcareca.com/medicare-pa-clinical-policies.html',
  'https://www.wellcare.com/en/hawaii/providers/medicare/claims/payment-policy'],
 'wellcare by trillium advantage': ['https://www.trilliumohp.com/providers/resources/clinical-payment-policies2.html',
  'https://www.trilliumohp.com/providers/resources/CPG.html'],
 'wellcare of kentucky': ['https://www.wellcareky.com/providers/tools/clinical-guidelines.html',
  'https://www.wellcareky.com/providers/medicaid/claims/payment-policy.html',
  'https://www.wellcare.com/en/kentucky/providers/clinical-guidelines/ccg-list'],
 'wellcare of north carolina': ['https://www.wellcarenc.com/providers/tools/clinical-coverage-medical-policy-updates.html',
  'https://www.wellcarenc.com/providers/tools/clinical-guidelines.html'],
 'wellcare prime by absolute total care': ['https://www.absolutetotalcare.com/providers/resources/payment-policies.html',
  'https://www.absolutetotalcare.com/providers/resources/clinical-payment-policies.html',
  'https://www.absolutetotalcare.com/providers/resources/behavioral-health-clinical-policies.html',
  'https://www.absolutetotalcare.com/providers/quality-improvement/practice-guidelines.html'],
 'western sky community care': ['https://www.westernskycommunitycare.com/providers/resources/clinical-payment-policies.html',
  'https://www.westernskycommunitycare.com/providers/quality-improvement/practice-guidelines.html'],
 'youthcare healthchoice illinois': ['https://www.ilyouthcare.com/providers/provider-resources/clinical-payment-policies.html']}

centene_dict = {'centene_ambetter': ["https://www.ambetterofalabama.com/provider-resources/clinical-payment-policies.html",
                                     "https://ambetter.azcompletehealth.com/provider-resources/clinical-payment-policies.html",
                                     "https://ambetter.arhealthwellness.com/provider-resources/clinical-payment-policies.html",
                                     "https://www.healthnet.com/content/healthnet/en_us/providers/working-with-hn/medical_policies.html",
                                     "https://ambetter.sunshinehealth.com/provider-resources/clinical-payment-policies.html",
                                     "https://ambetter.pshpgeorgia.com/provider-resources/clinical-payment-policies.html",
                                     "https://www.ambetterofillinois.com//provider-resources/clinical-payment-policies.html",
                                     "https://ambetter.mhsindiana.com//provider-resources/clinical-payment-policies.html",
                                     "https://ambetter.sunflowerhealthplan.com//provider-resources/clinical-payment-policies.html",
                                     "https://ambetter.wellcareky.com//provider-resources/clinical-payment-policies.html",
                                     "https://ambetter.louisianahealthconnect.com//provider-resources/clinical-payment-policies.html",
                                     "https://www.ambettermeridian.com//provider-resources/clinical-payment-policies.html",
                                     "https://ambetter.magnoliahealthplan.com//provider-resources/clinical-payment-policies.html",
                                     "https://ambetter.homestatehealth.com//provider-resources/clinical-payment-policies.html",
                                     "https://ambetter.nebraskatotalcare.com//provider-resources/clinical-payment-policies.html",
                                     "https://ambetter.silversummithealthplan.com//provider-resources/clinical-payment-policies.html",
                                     "https://ambetter.nhhealthyfamilies.com//provider-resources/clinical-payment-policies.html",
                                     "https://ambetter.wellcarenewjersey.com//provider-resources/clinical-payment-policies.html",
                                     "https://ambetter.westernskycommunitycare.com//provider-resources/clinical-payment-policies.html",
                                     "https://www.ambetterofnorthcarolina.com//provider-resources/clinical-payment-policies.html",
                                     "https://ambetter.buckeyehealthplan.com//provider-resources/clinical-payment-policies.html",
                                     "https://www.ambetterofoklahoma.com//provider-resources/clinical-payment-policies.html",
                                     "https://ambetter.pahealthwellness.com//provider-resources/clinical-payment-policies.html",
                                     "https://ambetter.absolutetotalcare.com//provider-resources/clinical-payment-policies.html",
                                     "https://www.ambetteroftennessee.com//provider-resources/clinical-payment-policies.html",
                                     "https://ambetter.superiorhealthplan.com//provider-resources/clinical-payment-policies.html",
                                     "https://ambetter.coordinatedcarehealth.com//provider-resources/clinical-payment-policies.html",
                                     "https://www.healthnetoregon.com/for-providers/resources/clinical-payment-policies.html"
                                     ],

                'centene_medicaid': ["https://www.azcompletehealth.com/providers/resources/clinical-payment-policies1.html",
                                     "https://www.care1staz.com/providers/resources/practice-guidelines1.html",
                                     "https://www.arkansastotalcare.com/providers/resources/clinical-payment-policies.html",
                                     "https://www.healthnet.com/content/healthnet/en_us/providers/working-with-hn/medical_policies.html",
                                     "https://www.cahealthwellness.com/providers/resources/clinical-policies.html",
                                     "https://www.cahealthwellness.com/providers/resources/clinical-payment-policies.html",
                                     "https://www.mhn.com/providers/working-with-mhn/clinical-operations-practices/utilization-management/clinical-practice-guidelines.html",
                                     "https://www.delawarefirsthealth.com/providers/resources/clinical-payment-policies.html",
                                     "https://www.sunshinehealth.com/providers/utilization-management/clinical-payment-policies.html",
                                     "https://www.pshpgeorgia.com/providers/resources/clinical-payment-policies.html",
                                     "https://www.ohanahealthplan.com/providers/tools/clinical-guidelines.html",
                                     "https://www.ohanahealthplan.com/providers/medicaid/claims/payment-policy.html",
                                     "https://www.ilmeridian.com/providers/resources/clinical-payment-policies.html",
                                     "https://www.ilyouthcare.com/providers/provider-resources/clinical-payment-policies.html",
                                     "https://www.mhsindiana.com/providers/clinical-payment-policies.html",
                                     "https://www.iowatotalcare.com/providers/resources/clinical-payment-policies.html",
                                     "https://www.sunflowerhealthplan.com/providers/quality-improvement/practice-guidelines.html",
                                     "https://www.sunflowerhealthplan.com/providers/resources/clinical-payment-policies.html",
                                     "https://www.wellcare.com/en/Kentucky/Providers/Clinical-Guidelines",
                                     "https://www.wellcareky.com/providers/medicaid/claims/payment-policy.html",
                                     "https://www.louisianahealthconnect.com/providers/resources/clinical-payment-policies.html",
                                     "https://www.mimeridian.com/providers/resources/medical-policies.html",
                                     "https://mmp.mimeridian.com/provider/training-and-education/clinical-practice-guidelines.html",
                                     "https://www.magnoliahealthplan.com/providers/resources/clinical-payment-policies.html",
                                     "https://www.homestatehealth.com/providers/tools-resources/clinical-payment-policies.html",
                                     "https://www.nebraskatotalcare.com/providers/resources/clinical-payment-policies.html",
                                     "https://www.silversummithealthplan.com/providers/resources/COPY_clinical-payment-policies.html",
                                     "https://www.nhhealthyfamilies.com/providers/resources/clinical-payment-policies.html",
                                     "https://www.wellcare.com/New-Jersey/Providers/Clinical-Guidelines/CPGs",
                                     "https://www.wellcarenewjersey.com/providers/medicaid/claims/payment-policy.html",
                                     "https://www.westernskycommunitycare.com/providers/resources/clinical-payment-policies.html",
                                     "https://www.fideliscare.org/Provider/Provider-Policies",
                                     "https://network.carolinacompletehealth.com/resources/clinical-policies.html",
                                     "https://network.carolinacompletehealth.com/resources/payment-policies.html",
                                     "https://www.wellcare.com/North-Carolina/Providers/Clinical-Guidelines/CPGs",
                                     "https://www.wellcare.com/North-Carolina/Providers/Clinical-Guidelines/CCG-List",
                                     "https://www.buckeyehealthplan.com/providers/resources/clinical-payment-policies.html",
                                     "https://www.oklahomacompletehealth.com/providers/resources/clinical-payment-policies.html",
                                     "https://www.trilliumohp.com/providers/resources/clinical-payment-policies2.html",
                                     "https://www.pahealthwellness.com/providers/resources/clinical-payment-policies.html",
                                     "https://www.absolutetotalcare.com/providers/resources/clinical-payment-policies.html",
                                     "https://www.absolutetotalcare.com/providers/resources/payment-policies.html",
                                     "https://www.superiorhealthplan.com/providers/resources/clinical-payment-policies.html",
                                     "https://www.coordinatedcarehealth.com/providers/resources/clinical-payment-policies.html",
                                     "https://www.coordinatedcarehealth.com/providers/quality-improvement/practice-guidelines.html",
                                     "https://www.mhswi.com/providers/resources/clinical-payment-policies.html"
                                     ],

                'centene_wellcare_reimbursement': ["https://www.wellcare.com/Alabama/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/Alaska/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/Arizona/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/en/Arkansas/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/California/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/Colorado/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/Connecticut/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/District-of-Columbia/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/Delaware/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/en/Florida/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/Georgia/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/Hawaii/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/Idaho/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/Illinois/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/en/Indiana/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/Iowa/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/Kansas/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/Kentucky/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/en/Louisiana/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/en/Maine/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/Maryland/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/Massachusetts/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/Michigan/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/Minnesota/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/en/Mississippi/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/en/Missouri/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/Montana/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/Nebraska/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/Nevada/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/en/New-Hampshire/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/New-Jersey/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/New-Mexico/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/New-York/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/north-carolina/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/North-Dakota/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/en/Ohio/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/en/Oklahoma/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/Oregon/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/Pennsylvania/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/Rhode-Island/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/South-Carolina/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/South-Dakota/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/en/Tennessee/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/en/Texas/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/Utah/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/Vermont/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/Virginia/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/Washington/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/West-Virginia/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/Wisconsin/Providers/Medicare/Claims",
                                                   "https://www.wellcare.com/Wyoming/Providers/Medicare/Claims"
                                                   ],
                'centene_wellcare_payment': ["https://www.wellcare.com/Alabama/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/Alaska/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/Arizona/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/en/Arkansas/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/California/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/Colorado/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/Connecticut/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/District-of-Columbia/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/Delaware/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/en/Florida/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/Georgia/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/Hawaii/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/Idaho/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/Illinois/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/en/Indiana/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/Iowa/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/Kansas/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/Kentucky/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/en/Louisiana/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/en/Maine/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/Maryland/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/Massachusetts/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/Michigan/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/Minnesota/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/en/Mississippi/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/en/Missouri/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/Montana/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/en/New-Hampshire/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/New-Jersey/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/New-Mexico/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/New-York/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/north-carolina/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/North-Dakota/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/en/Ohio/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/Oregon/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/Pennsylvania/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/Rhode-Island/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/South-Carolina/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/South-Dakota/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/en/Tennessee/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/en/Texas/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/Utah/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/Vermont/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/Virginia/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/Washington/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/West-Virginia/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/Wisconsin/Providers/Medicare/Claims/Payment-Policy",
                                             "https://www.wellcare.com/Wyoming/Providers/Medicare/Claims/Payment-Policy"
                                             ],

                'centene_wellcare_CCG': ["https://www.wellcare.com/Alabama/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/Alaska/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/Arizona/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/en/Arkansas/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/California/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/Colorado/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/Connecticut/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/District-of-Columbia/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/Delaware/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/en/Florida/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/Georgia/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/Hawaii/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/Idaho/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/Illinois/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/en/Indiana/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/Iowa/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/Kansas/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/Kentucky/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/en/Louisiana/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/en/Maine/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/Maryland/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/Massachusetts/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/Michigan/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/Minnesota/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/en/Mississippi/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/en/Missouri/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/Montana/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/en/New-Hampshire/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/New-Jersey/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/New-Mexico/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/New-York/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/north-carolina/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/North-Dakota/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/en/Ohio/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/Oregon/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/Pennsylvania/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/Rhode-Island/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/South-Carolina/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/South-Dakota/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/en/Tennessee/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/en/Texas/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/Utah/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/Vermont/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/Virginia/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/Washington/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/West-Virginia/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/Wisconsin/Providers/Clinical-Guidelines/CCG-List",
                                         "https://www.wellcare.com/Wyoming/Providers/Clinical-Guidelines/CCG-List"
                                         ]}


centene_state_map = {
    "www.azcompletehealth.com": "Arizona",
    "www.care1staz.com": "Arizona",
    "www.arkansastotalcare.com": "Arkansas",
    "www.healthnet.com": "NA",
    "www.cahealthwellness.com": " California",
    "www.mhn.com": "NA",
    "www.delawarefirsthealth.com": "Delaware",
    "www.sunshinehealth.com": "NA",
    "www.pshpgeorgia.com": "Georgia",
    "www.ohanahealthplan.com": "NA",
    "www.ilmeridian.com": "NA",
    "www.ilyouthcare.com": "NA",
    "www.mhsindiana.com": "Indiana",
    "www.iowatotalcare.com": "Iowa",
    "www.sunflowerhealthplan.com": "NA",
    "www.wellcareky.com": "Kentucky",
    "www.louisianahealthconnect.com": "Louisiana",
    "mmp.mimeridian.com": "NA",
    "www.magnoliahealthplan.com": "NA",
    "www.homestatehealth.com": "NA",
    "www.nebraskatotalcare.com": "Nebraska",
    "www.silversummithealthplan.com": "NA",
    "www.nhhealthyfamilies.com": "New Hampshire",
    "www.wellcarenewjersey.com": "New Jersey",
    "www.westernskycommunitycare.com": "NA",
    "www.fideliscare.org": "NA",
    "network.carolinacompletehealth.com": "NA",
    "network.carolinacompletehealth.com": "NA",
    "www.buckeyehealthplan.com": "NA",
    "www.oklahomacompletehealth.com": "Oklahoma",
    "www.trilliumohp.com": "NA",
    "www.pahealthwellness.com": "NA",
    "www.absolutetotalcare.com": "NA",
    "www.superiorhealthplan.com": "NA",
    "www.coordinatedcarehealth.com": "NA",
    "www.mhswi.com": "NA",
    "www.ambetterofalabama.com": "Alabama",
    "ambetter.azcompletehealth.com": "Arizona",
    "ambetter.arhealthwellness.com": "Arkansas",
    "www.healthnet.com": "NA",
    "ambetter.sunshinehealth.com": "NA",
    "ambetter.pshpgeorgia.com": "Georgia",
    "www.ambetterofillinois.com": "Illinois",
    "ambetter.mhsindiana.com": "Indiana",
    "ambetter.sunflowerhealthplan.com": "NA",
    "ambetter.wellcareky.com": "NA",
    "ambetter.louisianahealthconnect.com": "Louisiana",
    "www.ambettermeridian.com": "NA",
    "ambetter.magnoliahealthplan.com": "NA",
    "ambetter.homestatehealth.com": "NA",
    "ambetter.nebraskatotalcare.com": "Nebraska",
    "ambetter.silversummithealthplan.com": "NA",
    "ambetter.nhhealthyfamilies.com": "New Hampshire",
    "ambetter.wellcarenewjersey.com": "Newjersey",
    "ambetter.westernskycommunitycare.com": "NA",
    "www.fideliscare.org": "NA",
    "www.ambetterofnorthcarolina.com": "North Carolina",
    "ambetter.buckeyehealthplan.com": "NA",
    "www.ambetterofoklahoma.com": "Oklahoma",
    "www.healthnetoregon.com": "Oregon",
    "ambetter.pahealthwellness.com": "Pennsylvania",
    "ambetter.absolutetotalcare.com": "NA",
    "www.ambetteroftennessee.com": "Tennessee",
    "ambetter.superiorhealthplan.com": "NA",
    "ambetter.coordinatedcarehealth.com": "NA",
}

cigna_dict = {
    'Administrative (Non-Clinical Topics)': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/categories/administrative.html?',
    'Behavioral Health Topics': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/categories/behavioral.html?',
    'Cardiac Imaging and Diagnostic Studies': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/categories/cardioimagediag.html?',
    'Durable Medical Equipment (DME)': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/categories/dme.html?',
    'Genetics': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/categories/genetics.html?',
    'Laboratory/Pathology': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/categories/laboratory.html?',
    'Medicine (Medical Treatments/Diagnostic Tests)': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/categories/medicine.html?',
    'Mixed Topics': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/categories/mixedtopics.html?',
    'Musculoskeletal Guidelines': 'https://www.evicore.com/cignamedicare',
    'OB/GYN (Includes Reproduction and Infertility)': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/categories/obgyn.html?',
    'Orthotics/Prosthetics': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/categories/orthotics.html?',
    'Other (Miscellaneous Categories)': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/categories/miscellaneous.html?',
    'Radiation Therapy': 'https://www.evicore.com/cignamedicare',
    'Radiology - High Technology (MR, CT, PET)': 'https://www.evicore.com/cignamedicare',
    'Radiology - Other': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/categories/radiology.html?',
    'Surgery': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/categories/surgery.html?',
    'Therapy (Physical/Occupational/General Rehabilitation)': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/categories/therapy.html?',
    'Transplants': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/categories/transplants.html?',
    'Pharmacy (Drugs, Vaccines & Biologics)': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/pharmacy_a-z.html',
    'Cigna National Formulary Policy': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/cnf_a-z.html',

}

cigna_policy_updates_dict = {'coveragePoliciesLatestUpdatesJanurary2016': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesJanurary2016.html',
                             'coveragePoliciesLatestUpdatesJanurary2017': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesJanurary2017.html',
                             'coveragePoliciesLatestUpdatesJanurary2018': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesJanurary2018.html',
                             'coveragePoliciesLatestUpdatesJanurary2019': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesJanurary2019.html',
                             'coveragePoliciesLatestUpdatesJanurary2020': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesJanurary2020.html',
                             'coveragePoliciesLatestUpdatesJanurary2021': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesJanurary2021.html',
                             'coveragePoliciesLatestUpdatesJanurary2022': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesJanurary2022.html',
                             'coveragePoliciesLatestUpdatesJanurary2023': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesJanurary2023.html',
                             'coveragePoliciesLatestUpdatesFebruary2016': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesFebruary2016.html',
                             'coveragePoliciesLatestUpdatesFebruary2017': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesFebruary2017.html',
                             'coveragePoliciesLatestUpdatesFebruary2018': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesFebruary2018.html',
                             'coveragePoliciesLatestUpdatesFebruary2019': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesFebruary2019.html',
                             'coveragePoliciesLatestUpdatesFebruary2020': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesFebruary2020.html',
                             'coveragePoliciesLatestUpdatesFebruary2021': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesFebruary2021.html',
                             'coveragePoliciesLatestUpdatesFebruary2022': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesFebruary2022.html',
                             'coveragePoliciesLatestUpdatesFebruary2023': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesFebruary2023.html',
                             'coveragePoliciesLatestUpdatesMarch2016': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesMarch2016.html',
                             'coveragePoliciesLatestUpdatesMarch2017': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesMarch2017.html',
                             'coveragePoliciesLatestUpdatesMarch2018': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesMarch2018.html',
                             'coveragePoliciesLatestUpdatesMarch2019': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesMarch2019.html',
                             'coveragePoliciesLatestUpdatesMarch2020': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesMarch2020.html',
                             'coveragePoliciesLatestUpdatesMarch2021': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesMarch2021.html',
                             'coveragePoliciesLatestUpdatesMarch2022': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesMarch2022.html',
                             'coveragePoliciesLatestUpdatesMarch2023': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesMarch2023.html',
                             'coveragePoliciesLatestUpdatesApril2016': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesApril2016.html',
                             'coveragePoliciesLatestUpdatesApril2017': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesApril2017.html',
                             'coveragePoliciesLatestUpdatesApril2018': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesApril2018.html',
                             'coveragePoliciesLatestUpdatesApril2019': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesApril2019.html',
                             'coveragePoliciesLatestUpdatesApril2020': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesApril2020.html',
                             'coveragePoliciesLatestUpdatesApril2021': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesApril2021.html',
                             'coveragePoliciesLatestUpdatesApril2022': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesApril2022.html',
                             'coveragePoliciesLatestUpdatesApril2023': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesApril2023.html',
                             'coveragePoliciesLatestUpdatesMay2016': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesMay2016.html',
                             'coveragePoliciesLatestUpdatesMay2017': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesMay2017.html',
                             'coveragePoliciesLatestUpdatesMay2018': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesMay2018.html',
                             'coveragePoliciesLatestUpdatesMay2019': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesMay2019.html',
                             'coveragePoliciesLatestUpdatesMay2020': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesMay2020.html',
                             'coveragePoliciesLatestUpdatesMay2021': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesMay2021.html',
                             'coveragePoliciesLatestUpdatesMay2022': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesMay2022.html',
                             'coveragePoliciesLatestUpdatesMay2023': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesMay2023.html',
                             'coveragePoliciesLatestUpdatesJune2016': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesJune2016.html',
                             'coveragePoliciesLatestUpdatesJune2017': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesJune2017.html',
                             'coveragePoliciesLatestUpdatesJune2018': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesJune2018.html',
                             'coveragePoliciesLatestUpdatesJune2019': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesJune2019.html',
                             'coveragePoliciesLatestUpdatesJune2020': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesJune2020.html',
                             'coveragePoliciesLatestUpdatesJune2021': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesJune2021.html',
                             'coveragePoliciesLatestUpdatesJune2022': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesJune2022.html',
                             'coveragePoliciesLatestUpdatesJune2023': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesJune2023.html',
                             'coveragePoliciesLatestUpdatesJuly2016': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesJuly2016.html',
                             'coveragePoliciesLatestUpdatesJuly2017': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesJuly2017.html',
                             'coveragePoliciesLatestUpdatesJuly2018': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesJuly2018.html',
                             'coveragePoliciesLatestUpdatesJuly2019': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesJuly2019.html',
                             'coveragePoliciesLatestUpdatesJuly2020': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesJuly2020.html',
                             'coveragePoliciesLatestUpdatesJuly2021': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesJuly2021.html',
                             'coveragePoliciesLatestUpdatesJuly2022': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesJuly2022.html',
                             'coveragePoliciesLatestUpdatesJuly2023': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesJuly2023.html',
                             'coveragePoliciesLatestUpdatesAugust2016': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesAugust2016.html',
                             'coveragePoliciesLatestUpdatesAugust2017': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesAugust2017.html',
                             'coveragePoliciesLatestUpdatesAugust2018': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesAugust2018.html',
                             'coveragePoliciesLatestUpdatesAugust2019': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesAugust2019.html',
                             'coveragePoliciesLatestUpdatesAugust2020': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesAugust2020.html',
                             'coveragePoliciesLatestUpdatesAugust2021': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesAugust2021.html',
                             'coveragePoliciesLatestUpdatesAugust2022': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesAugust2022.html',
                             'coveragePoliciesLatestUpdatesAugust2023': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesAugust2023.html',
                             'coveragePoliciesLatestUpdatesSeptember2016': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesSeptember2016.html',
                             'coveragePoliciesLatestUpdatesSeptember2017': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesSeptember2017.html',
                             'coveragePoliciesLatestUpdatesSeptember2018': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesSeptember2018.html',
                             'coveragePoliciesLatestUpdatesSeptember2019': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesSeptember2019.html',
                             'coveragePoliciesLatestUpdatesSeptember2020': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesSeptember2020.html',
                             'coveragePoliciesLatestUpdatesSeptember2021': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesSeptember2021.html',
                             'coveragePoliciesLatestUpdatesSeptember2022': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesSeptember2022.html',
                             'coveragePoliciesLatestUpdatesSeptember2023': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesSeptember2023.html',
                             'coveragePoliciesLatestUpdatesOctober2016': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesOctober2016.html',
                             'coveragePoliciesLatestUpdatesOctober2017': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesOctober2017.html',
                             'coveragePoliciesLatestUpdatesOctober2018': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesOctober2018.html',
                             'coveragePoliciesLatestUpdatesOctober2019': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesOctober2019.html',
                             'coveragePoliciesLatestUpdatesOctober2020': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesOctober2020.html',
                             'coveragePoliciesLatestUpdatesOctober2021': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesOctober2021.html',
                             'coveragePoliciesLatestUpdatesOctober2022': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesOctober2022.html',
                             'coveragePoliciesLatestUpdatesOctober2023': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesOctober2023.html',
                             'coveragePoliciesLatestUpdatesNovember2016': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesNovember2016.html',
                             'coveragePoliciesLatestUpdatesNovember2017': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesNovember2017.html',
                             'coveragePoliciesLatestUpdatesNovember2018': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesNovember2018.html',
                             'coveragePoliciesLatestUpdatesNovember2019': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesNovember2019.html',
                             'coveragePoliciesLatestUpdatesNovember2020': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesNovember2020.html',
                             'coveragePoliciesLatestUpdatesNovember2021': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesNovember2021.html',
                             'coveragePoliciesLatestUpdatesNovember2022': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesNovember2022.html',
                             'coveragePoliciesLatestUpdatesNovember2023': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesNovember2023.html',
                             'coveragePoliciesLatestUpdatesDecember2016': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesDecember2016.html',
                             'coveragePoliciesLatestUpdatesDecember2017': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesDecember2017.html',
                             'coveragePoliciesLatestUpdatesDecember2018': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesDecember2018.html',
                             'coveragePoliciesLatestUpdatesDecember2019': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesDecember2019.html',
                             'coveragePoliciesLatestUpdatesDecember2020': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesDecember2020.html',
                             'coveragePoliciesLatestUpdatesDecember2021': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesDecember2021.html',
                             'coveragePoliciesLatestUpdatesDecember2022': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesDecember2022.html',
                             'coveragePoliciesLatestUpdatesDecember2023': 'https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/policyUpdates/coveragePoliciesLatestUpdatesDecember2023.html'}


centene_lob_dict = {'medicaid': 'Medicaid', 'medicare': 'Medicare'}

centene_sl_dict = {'drugpolicies': 'Drug Policies',
                   'statepolicies': 'State Policies',
                   'paymentpolicies': 'Payment Policies',
                   'pharmacypolicies': 'Pharmacy Policies',
                   'clinicalpolicies': 'Clinical Policies',
                   'behavioralpolicies': 'Behavioral Policies',
                   'visionpolicies': 'Vision Policies',
                   'researchclinicalcare': 'Research Clinical Care',
                   'practiceguidelines': 'Practice Guidelines'}

cigna_sl_dict = {'medical': 'Medical Policies',
                 'cnf': 'Coverage Policies',
                 'pharmacy': 'Pharmacy Policies',
                 'clinicalguidelines': 'Clincial Guidelines'}


centene_null_state_mapping = {
    'www.healthnet.com': 'California',
    'www.mhn.com': 'California',
    'www.sunshinehealth.com': 'Florida',
    'www.ohanahealthplan.com': 'Hawaii',
    'www.ilmeridian.com': 'Illinois',
    'www.ilyouthcare.com': 'Illinois',
    'www.sunflowerhealthplan.com': 'Kansas',
    'mmp.mimeridian.com': 'Michigan',
    'www.magnoliahealthplan.com': 'Mississippi',
    'www.homestatehealth.com': 'Missouri',
    'www.silversummithealthplan.com': 'Nevada',
    'www.westernskycommunitycare.com': 'New Mexico',
    'www.fideliscare.org': 'New York',
    'network.carolinacompletehealth.com': 'North Carolina',
    'www.buckeyehealthplan.com': 'Ohio',
    'www.trilliumohp.com': 'Oklahoma',
    'www.pahealthwellness.com': 'Pennsylvania',
    'www.absolutetotalcare.com': 'South Carolina',
    'www.superiorhealthplan.com': 'Texas',
    'www.coordinatedcarehealth.com': 'Washington',
    'www.mhswi.com': 'Wisconsin',
    'ambetter.sunshinehealth.com': 'Florida',
    'ambetter.sunflowerhealthplan.com': 'Kansas',
    'ambetter.wellcareky.com': 'Kentucky',
    "www.ambettermeridian.com": 'Michigan',
    'ambetter.magnoliahealthplan.com': 'Mississippi',
    'ambetter.homestatehealth.com': 'Missouri',
    "ambetter.silversummithealthplan.com": 'Nevada',
    'ambetter.westernskycommunitycare.com': 'New Mexico',
    'ambetter.buckeyehealthplan.com': 'Ohio',
    'ambetter.absolutetotalcare.com': 'South Carolina',
    'ambetter.superiorhealthplan.com': 'Texas',
    'ambetter.coordinatedcarehealth.com': 'Washington'
}


def remove_special_chars(string):
    return re.sub('[^A-Za-z0-9]+', '', string)


def lob_sl_mapper(link, diction):

    lob_sl = 'NA'
    words_list = link.split("/")
    lst1 = [x. lower() for x in words_list]
    out_list = list(map(remove_special_chars, lst1))
    if list(set(out_list) & set(diction.keys())):
        lob_sl = diction.get(
            list(set(out_list) & set(diction.keys()))[0], 'NA')
    return lob_sl


SENDER_MAIL = 'rightpx@zignaai.com'
RECIPIENTS_LIST = ['suriya@zignaai.com',
                   'netra@zignaai.com']



COLUMN_PREFIX = 'extrctn_'


def add_column_prefix(df, COLUMN_PREFIX):
    return [COLUMN_PREFIX + col for col in df.columns]


devoted_base_url = ['https://www.devoted.com/providers/payment-policies/']
cms_trans_pub_base_url = [(100, "https://www.cms.gov/training-education/healthcare-provider-resources/mln-publications-multimedia/articles?items_per_page=100&combine=&field_dyna_year_value=&page=", 'Transmittals_and_MLN_Articles'),
                          (1, "https://www.cms.gov/training-education/medicare-learning-network/compliance?page=", 'Publications')]

devoted_state_mapping_dictionary = {'Alabama': 'AL',
                                    'Arizona': 'AZ',
                                    'Colorado': 'CO', 
                                    'Florida': 'FL', 
                                    'Hawaii': 'HI', 
                                    'Illinois': 'IL', 
                                    'North Carolina': 'NC',
                                    'Ohio': 'OH', 
                                    'Oregon': 'OR', 
                                    'Pennsylvania': 'PA', 
                                    'South Carolina': 'SC', 
                                    'Tennessee': 'TN', 
                                    'Texas': 'TX'}

devoted_states_list = ['AL', 'AZ', 'CO', 'FL', 'HI','IL', 'NC', 'OH', 'OR', 'PA', 'SC', 'TN', 'TX']
webpage_devoted = r"https://www.devoted.com/service-area/"

# CMS_MCD_MAIN_BASE_URL = "https://www.cms.gov/medicare-coverage-database/downloads/downloads.aspx"
CMS_MCD_ZIP_URL = 'https://downloads.cms.gov/medicare-coverage-database/downloads/exports/all_data.zip'
CMS_MCD_FILE_NAME = CMS_MCD_ZIP_URL.split('/')[-1].replace('.zip','')

CMS_MCD_BASE_URLS = {
                        "ARTICLES" : ["zai-reference-data",
                                        f"reference_files/CMS_MCD_POLICIES/{DEST_FOLDER_LEVEL_5}/{CMS_MCD_FILE_NAME}/all_article/all_article_csv/article.csv",
                                        "article",
                                        "articleid",
                                        "ver",
                                        "article_id",
                                        "article_version",
                                        "title",
                                        "article_pub_date",
                                        "NA",
                                        "NA"],
                        "LCD"       : ["zai-reference-data",
                                        f"reference_files/CMS_MCD_POLICIES/{DEST_FOLDER_LEVEL_5}/{CMS_MCD_FILE_NAME}/all_lcd/all_lcd_csv/lcd.csv",
                                        "lcd",
                                        "lcdid",
                                        "ver",
                                        "lcd_id",
                                        "lcd_version",
                                        "title",
                                        "orig_det_eff_date",
                                        "NA",
                                        "NA"],
                        "NCD"       : ["zai-reference-data",
                                        f"reference_files/CMS_MCD_POLICIES/{DEST_FOLDER_LEVEL_5}/{CMS_MCD_FILE_NAME}/ncd/ncd_csv/ncd_trkg.csv",                                       
                                        "ncd",
                                        "ncdid",
                                        "ncdver",
                                        "NCD_id",
                                        "NCD_vrsn_num",
                                        "NCD_mnl_sect_title",
                                        "NCD_efctv_dt",
                                        "NA",
                                        "NA"]
                    }